lijim/monks-and-mages

- src/client/components/App/App.tsx
- src/client/components/IntroScreen/IntroScreen.tsx
- src/client/components/IntroScreen/index.ts
- src/client/components/NameChanger/NameChanger.spec.tsx
- src/client/components/NameChanger/NameChanger.tsx
- src/client/components/NameChanger/index.ts
Adds a basic component that shows either:
- a name changer if you don't have a name yet
- just a name if you've selected one.
Demo:
https://user-images.githubusercontent.com/1839462/155830829-96d98f36-ff9b-4f11-a85d-606aeb3df780.mov
> Add a intro screen component

- src/client/components/WebSockets/WebSockets.tsx
Previously blindly following the tutorial led to bug where the socket instance was getting initialized on every single render (e.g. when redux changed, the socket was created anew)
To fix this, I put ws and socket behind useState values.
> Fix: make initialization only happen once for web sockets

- package.json
- src/client/components/WebSockets/WebSockets.tsx
- src/server/index.ts
- webpack.config.js
- yarn.lock
https://admin.socket.io/#/sockets
> Add admin-ui for socket.io

- README.md
- src/client/components/RoomSquare/RoomSquare.tsx
- src/factories/board/makeNewBoard.spec.ts
- src/factories/board/makeNewBoard.ts
- src/factories/deck/makeDeck.ts
- src/factories/player/makeNewPlayer.spec.ts
- src/factories/player/makeNewPlayer.ts
- src/server/index.ts
- src/types/board.ts
Building methods to easily:
- make a `Player` object, given a `DeckList`
- make a `Board` given player names (this will eventually take `DeckList`'s too, but focusing on game engine first, before deck-building aspects of this game)
> Factory methods for board / player

- src/client/components/App/App.tsx
- src/client/components/GameBoard/GameBoard.spec.tsx
- src/client/components/GameBoard/GameBoard.tsx
- src/client/components/GameBoard/index.ts
- src/client/components/WebSockets/WebSockets.tsx
- src/client/redux/board/board.ts
- src/client/redux/board/index.ts
- src/client/redux/store.ts
- src/server/index.ts
The server now emits the board state down to the sockets whenever a game is started
Pre-requisite for #13
> Emit board state on joining game to redux

- src/client/components/WebSockets/WebSockets.tsx
- src/types.ts
- src/types/gameActions.ts
Introduces a framework for implementing player actions for the core game engine.
- Players take game actions
- Engine interprets the game action by type
- Engine validates if the player emitting the action is the active player
- Engine checks to see if action is performable
- Engine performs action
- Server emits an updated board state down to the users
> Game Actions Framework

- package.json
- src/factories/cards/makeCard.spec.ts
- src/factories/cards/makeCards.ts
- src/types/cards.ts
- yarn.lock
> UUID's for cards

- README.md
- src/client/components/GameBoard/GameBoard.tsx
- src/factories/board/makeNewBoard.ts
- src/server/gameEngine/gameEngine.spec.ts
- src/server/gameEngine/gameEngine.ts
- src/server/gameEngine/index.ts
- src/server/index.ts
- src/server/sockets/index.ts
- src/server/sockets/sockets.ts
- src/types/board.ts
- src/types/gameActions.ts
Adds in a game engine + a basic game action of passing the turn over.
Closes #39 
https://user-images.githubusercontent.com/1839462/156787737-2c1a070a-0e07-414a-8f87-d25bc52b5ee7.mov
> "Pass Turn" game action + gameEngine

- README.md
- src/client/components/App/App.tsx
- src/client/components/GameBoard/GameBoard.spec.tsx
- src/client/components/GameBoard/GameBoard.tsx
- src/client/components/OtherPlayerBoard/OtherPlayerBoard.tsx
- src/client/components/PlayerBriefInfo/PlayerBriefInfo.spec.tsx
- src/client/components/PlayerBriefInfo/PlayerBriefInfo.tsx
- src/client/components/PlayerBriefInfo/index.ts
- src/client/components/SelfPlayerBoard/SelfPlayerBoard.tsx
- src/constants/colors.ts
Adds a display component for showing information (# of cards in deck remaining, # of cards in hand, health, name) about a player
Incorporated this component on the GameBoard component (which I'm starting to want to rename GameDisplay)
Closes #36
> PlayerBriefInfo component

- src/client/components/App/App.tsx
- src/client/components/GameBoard/index.ts
- src/client/components/GameDisplay/GameDisplay.spec.tsx
- src/client/components/GameDisplay/GameDisplay.tsx
- src/client/components/GameDisplay/index.ts
- src/client/components/HandOfCards/HandOfCards.spec.tsx
- src/client/components/HandOfCards/HandOfCards.tsx
- src/client/components/HandOfCards/index.ts
- src/client/components/SelfPlayerBoard/SelfPlayerBoard.spec.tsx
- src/client/components/SelfPlayerBoard/SelfPlayerBoard.tsx
- src/constants/colors.ts
Renamed `GameBoard` as `GameDisplay`.
Added components that make a rough draft that looks like this:
> Initial Implementation of GameDisplay

- src/client/components/GameDisplay/GameDisplay.tsx
- src/client/components/HandOfCards/HandOfCards.tsx
- src/server/homepage.html
> Give cards in `HandOfCards` component equal spacing

- src/client/components/App/App.tsx
- src/client/components/CardGridItem/CardGridItem.tsx
- src/client/components/HandOfCards/HandOfCards.tsx
- src/client/components/PlayerBoardSection/PlayerBoardSection.tsx
- src/client/components/ResourceCardGridItem/ResourceCardGridItem.tsx
- src/client/components/WebSockets/WebSockets.tsx
- src/client/components/WebSockets/handleClickOnCard.ts
- src/client/index.tsx
- src/server/gameEngine/gameEngine.spec.ts
- src/server/gameEngine/gameEngine.ts
Closes #48 
https://user-images.githubusercontent.com/1839462/156937692-4a3259b1-4037-4e6d-887b-44526b40f1eb.mov
> Add 'deploy resource' to game engine

- src/client/components/CardFrame/CardFrame.tsx
- src/client/components/PlayerBoardSection/PlayerBoardSection.tsx
- src/client/components/ResourceCardGridItem/ResourceCardGridItem.tsx
- src/client/components/WebSockets/handleClickOnCard.ts
- src/server/gameEngine/gameEngine.spec.ts
- src/server/gameEngine/gameEngine.ts
> Tap resource game action

- src/transformers/canPlayerPayForCard/canPlayerPayForCard.ts
- src/transformers/canPlayerPayForCard/canPlayerPayForCards.spec.ts
- src/transformers/canPlayerPayForCard/index.ts
- src/transformers/payForCard/index.ts
- src/transformers/payForCard/payForCard.spec.ts
- src/transformers/payForCard/payForCard.ts
> Helpers for paying for cards

- src/client/components/CardGridItem/CardGridItem.tsx
- src/client/components/GameManager/handleClickOnCard.ts
- src/client/components/UnitGridItem/UnitGridItem.tsx
- src/server/gameEngine/gameEngine.spec.ts
- src/server/gameEngine/gameEngine.ts
Closes #57
Demo (need to do a spike on the overall spacing and display of the units, but this is for MVP)
> Add 'Deploy Unit' game action

- src/client/components/CardFrame/CardFrame.tsx
- src/client/components/CardGridItem/CardGridItem.spec.tsx
- src/client/components/DeckList/DeckList.spec.tsx
- src/client/components/GameManager/GameManager.tsx
- src/client/components/GameManager/handleClickOnCard.ts
- src/client/components/PlayerBoardSection/PlayerBoardSection.spec.tsx
- src/client/components/PlayerBoardSection/PlayerBoardSection.tsx
- src/client/components/SelfPlayerInfo/SelfPlayerInfo.tsx
- src/client/components/UnitGridItem/UnitGridItem.spec.tsx
- src/client/components/UnitGridItem/UnitGridItem.tsx
- src/client/redux/clientSideGameExtras/clientSideGameExtras.ts
- src/client/redux/clientSideGameExtras/index.ts
- src/client/redux/selectors.spec.ts
- src/client/redux/selectors.ts
- src/client/redux/store.ts
- src/server/gameEngine/gameEngine.spec.ts
- src/server/gameEngine/gameEngine.ts
Part of #58 
https://user-images.githubusercontent.com/1839462/156977730-eedfde5c-19f3-4235-a632-fdd4862ec7a2.mov
> Add ability to select an attacking unit

- src/client/components/GameManager/GameManager.tsx
- src/client/components/GameManager/handleClickOnCard.spec.ts
- src/client/components/GameManager/handleClickOnPlayer.spec.ts
- src/client/components/GameManager/handleClickPlayer.ts
- src/client/components/PlayerBriefInfo/PlayerBriefInfo.tsx
- src/client/redux/clientSideGameExtras/clientSideGameExtras.ts
- src/constants/gameConstants.ts
- src/factories/player/makeNewPlayer.ts
- src/server/gameEngine/gameEngine.spec.ts
- src/server/gameEngine/gameEngine.ts
Closes #58
https://user-images.githubusercontent.com/1839462/157344108-9b5de4d9-bcb3-491c-bbe3-55b8b7860fde.mov
> Implement attack against player

- src/cardDb/spells/spells.ts
- src/client/components/CardGridItem/CardGridItem.tsx
- src/client/components/GameManager/handleClickOnCard.ts
- src/client/components/SpellGridItem/SpellGridItem.tsx
- src/constants/gameConstants.ts
- src/factories/board/makeNewBoard.ts
- src/factories/deck/makeDeck.ts
- src/factories/player/makeNewPlayer.ts
- src/server/gameEngine/gameEngine.spec.ts
- src/server/gameEngine/gameEngine.ts
Does not actually resolve the effects yet - that will be in an upcoming PR
For: #59
Demo:
https://user-images.githubusercontent.com/1839462/157354634-59b871ef-76ef-4fa9-9a90-636da7d5a1ad.mov
> Add spellcasting

- src/client/components/GameManager/GameManager.tsx
- src/client/redux/selectors.spec.ts
- src/client/redux/selectors.ts
- src/server/resolveEffect/index.ts
- src/server/resolveEffect/resolveEffect.spec.ts
- src/server/resolveEffect/resolveEffect.ts
- src/server/sockets/sockets.ts
- src/types.ts
- src/types/effects.ts
Closes: #78
Closes: #82
https://user-images.githubusercontent.com/1839462/157579115-afa870a1-9c86-40b7-888e-8340e00920ac.mov
> Add ability to draw cards with 'Generous Geyser'

- src/client/components/GameManager/handleClickOnCard.spec.ts
- src/client/components/GameManager/handleClickOnCard.ts
- src/client/components/GameManager/handleClickOnPlayer.spec.ts
- src/client/components/GameManager/handleClickPlayer.ts
- src/client/components/WebSockets/WebSockets.tsx
- src/server/resolveEffect/resolveEffect.spec.ts
- src/server/resolveEffect/resolveEffect.ts
- src/server/sockets/sockets.ts
- src/types.ts
Closes #77
Closes #79
Closes #83
https://user-images.githubusercontent.com/1839462/157592737-1f9a82a1-a1f8-4db6-ba3d-9feaa5caf0d4.mov
Casting ember spear on an opponent ^
> Add 'deal damage' effect

- src/server/sockets/socket.spec.ts
- src/server/sockets/sockets.ts
Closes: #26
Before (players can join multiple rooms):
https://user-images.githubusercontent.com/1839462/157608609-2700f656-9ca5-4c51-9c23-ad5dd7fd5513.mov
Now (players can only join one room at a time):
https://user-images.githubusercontent.com/1839462/157608658-4148f4ef-b53d-47f2-9a2d-ca1b1106836b.mov
> Allow players to only join one room at a time

- src/client/components/GameDisplay/GameDisplay.spec.tsx
- src/client/components/GameDisplay/GameDisplay.tsx
- src/client/components/PlayerBoardSection/PlayerBoardSection.tsx
Closes: #96
https://user-images.githubusercontent.com/1839462/157794519-af17dc60-1dbc-4b88-84d0-a14d1e2ee263.mov
> Add visual indicator of current effect

- src/client/components/GameManager/GameManager.spec.tsx
- src/client/components/GameManager/GameManager.tsx
Closes: #97
https://user-images.githubusercontent.com/1839462/157800449-ead8f23a-7cc7-487c-94d8-b7fa045294a9.mov
> Add 2-second delay to auto-resolving effects

- README.md
- src/client/components/CardFrame/CardFrame.tsx
- src/client/components/UnitGridItem/UnitGridItem.spec.tsx
- src/client/components/UnitGridItem/UnitGridItem.tsx
- src/constants/colors.ts
- src/server/gameEngine/gameEngine.spec.ts
- src/server/gameEngine/gameEngine.ts
- src/server/index.ts
- src/server/resolveEffect/resolveEffect.spec.ts
- src/server/resolveEffect/resolveEffect.ts
Closes: #91, Closes: #100
Also cleaned up some of the logic around processing if a unit goes to the cemetery and what happens if it does.
Visual demo:
https://user-images.githubusercontent.com/1839462/158001894-211cffe6-73f3-4c86-be5b-43fd5fbdfe86.mov
> Add buff system

- src/cardDb/units/units.ts
- src/client/components/Rooms/Rooms.spec.tsx
- src/client/components/Rooms/Rooms.tsx
- src/client/components/WebSockets/WebSockets.tsx
- src/factories/board/makeNewBoard.spec.ts
- src/factories/board/makeNewBoard.ts
- src/server/sockets/sockets.ts
- src/test-utils/test-utils.tsx
- src/types.ts
Lets players select between 2 different decks at the start of the game
Closes #125
Demo:
https://user-images.githubusercontent.com/1839462/158010081-53d0fcde-3865-4331-9b6c-92aa6e3dab07.mov
> Allow for deck selection

- src/client/components/Rooms/Rooms.tsx
There was a regression in the recent lobby change commits b/c of not having an onSubmit on the form here:
https://github.com/lijim/monks-and-mages/pull/133/files#diff-9edc7fa06827cfb587f5bdcdd78f180b257057bf7c9760bf33a71a7c484ac751R92
> Fix: not able to create new room

- src/cardDb/units/units.ts
- src/client/components/CardGridItem/CardGridItem.tsx
- src/server/gameEngine/gameEngine.spec.ts
- src/server/gameEngine/gameEngine.ts
Also rebalanced the assassin to be ranged
Closes: #119
> Implement 'poisonous'

- src/client/components/GameDisplay/GameDisplay.spec.tsx
- src/client/components/GameDisplay/GameDisplay.tsx
- src/client/redux/selectors.spec.ts
- src/client/redux/selectors.ts
> Show the latest effect for all players

- README.md
- src/cardDb/spells/spells.ts
- src/cardDb/units/units.ts
- src/constants/lobbyConstants.ts
- src/factories/board/makeNewBoard.ts
- src/factories/deck/makeDeck.ts
- src/mocks/spells.ts
- src/server/resolveEffect/resolveEffect.spec.ts
- src/server/resolveEffect/resolveEffect.ts
- src/transformers/transformEffectsToRulesText/transformEffectsToRulesText.ts
- src/transformers/transformEffectsToRulesText/transformEffectstoRulesText.spec.ts
- src/types/cards.ts
- src/types/effects.ts
- condensed ramp effects into 1 single effect
- implemented ramp effect
https://user-images.githubusercontent.com/1839462/158040434-64dbe895-676c-440f-91d5-6ebdfcbdd9cf.mov
Closes: #86
> Ramp effect

- README.md
- src/client/components/GameManager/handleClickOnCard.spec.ts
- src/client/components/GameManager/handleClickOnCard.ts
- src/client/components/GameManager/handleClickOnPlayer.spec.ts
- src/client/components/GameManager/handleClickPlayer.ts
- src/client/components/SelfPlayerInfo/SelfPlayerInfo.spec.tsx
- src/client/components/SelfPlayerInfo/SelfPlayerInfo.tsx
- src/client/redux/selectors.spec.ts
- src/client/redux/selectors.ts
- src/factories/player/makeNewPlayer.ts
- src/server/gameEngine/gameEngine.spec.ts
- src/server/gameEngine/gameEngine.ts
- src/types/board.ts
When a player has won, they no longer have the ability to interact with the board
> Prevent player actions if game is over

- src/client/components/CenterPromptBox/CenterPromptBox.spec.tsx
- src/client/components/CenterPromptBox/CenterPromptBox.tsx
- src/client/components/CenterPromptBox/index.ts
- src/client/components/GameDisplay/GameDisplay.tsx
- src/constants/colors.ts
- src/factories/board/makeNewBoard.ts
- src/server/gameEngine/gameEngine.spec.ts
- src/server/gameEngine/gameEngine.ts
- src/server/sockets/sockets.ts
- src/types/board.ts
- src/types/gameActions.ts
Demo:
https://user-images.githubusercontent.com/1839462/158047641-4bc77d0d-b893-4136-a241-37f9c0aac77b.mov
Closes #137
> Add mulligan decision to game

- src/cardDb/units/units.ts
- src/client/components/NameChanger/NameChanger.tsx
- src/server/homepage.html
- src/server/resolveEffect/resolveEffect.spec.ts
- src/server/resolveEffect/resolveEffect.ts
- src/types/effects.ts
Closes: #89 
Demo:
https://user-images.githubusercontent.com/1839462/158137530-10794e95-2c74-48dc-b549-5848942e70b2.mov
> Add heal effect

- src/client/components/GameDisplay/GameDisplay.spec.tsx
- src/client/components/GameDisplay/GameDisplay.tsx
- src/client/components/PlayerBriefInfo/PlayerBriefInfo.tsx
- src/constants/colors.ts
- src/factories/chat/index.ts
- src/factories/chat/makeChatMsg.spec.ts
- src/factories/chat/makeChatMsg.ts
- src/server/gameEngine/gameEngine.spec.ts
- src/server/gameEngine/gameEngine.ts
- src/types/chat.ts
Closes: #163
Inspo from: https://codepen.io/haja-ran/pen/yWwLYM
> Add chat boxes (deploying units)

- src/client/components/GameDisplay/GameDisplay.tsx
> Scroll chat to bottom automatically

- src/client/components/NameChanger/NameChanger.tsx
- src/server/gameEngine/gameEngine.spec.ts
- src/server/gameEngine/gameEngine.ts
- src/server/resolveEffect/resolveEffect.spec.ts
- src/server/resolveEffect/resolveEffect.ts
Closes: #164
Closes: #165
https://user-images.githubusercontent.com/1839462/158521363-e7e482af-6a02-432e-85ce-c4ac519f5f28.mov
> Display chats for spells and effects

- src/server/gameEngine/gameEngine.spec.ts
- src/server/gameEngine/gameEngine.ts
- src/server/resolveEffect/resolveEffect.spec.ts
- src/server/resolveEffect/resolveEffect.ts
Demos:
Mulligans
https://user-images.githubusercontent.com/1839462/158530601-f66334dc-b340-4c7d-a441-26038a48b884.mov
Attacks
https://user-images.githubusercontent.com/1839462/158532267-f75b0729-8555-4c7a-9781-b2d41e91cce1.mov
> Chat messages (mulligans + attacks)

- src/server/gameEngine/gameEngine.spec.ts
- src/server/gameEngine/gameEngine.ts
> messages for attacking opposing players

- src/client/components/App/App.tsx
- src/client/components/IntroScreen/IntroScreen.tsx
- src/client/components/NameChanger/NameChanger.tsx
- src/client/components/Rooms/Rooms.tsx
> New Rooms Screen

- README.md
- src/client/components/HandOfCards/HandOfCards.tsx
Add more spacing between cards in the hand:
Before:
After:
> More spacing for cards in hand

- package.json
- src/server/homepage.html
- src/server/index.ts
- webpack.config.js
- yarn.lock
Closes: https://github.com/lijim/monks-and-mages/issues/181
- added HtmlWebpackPlugin and made it dynamically render the homepage.html as `dist/public/js/index.html`
Based on guide here:
https://webpack.js.org/guides/caching/
https://webpack.js.org/configuration/output/#outputfilename[](https://github.com/lijim)
> Add cache-busting via webpack

- src/cardDb/spells/spells.ts
- src/constants/deckLists.ts
- src/constants/lobbyConstants.ts
- src/server/gameEngine/gameEngine.spec.ts
- src/server/gameEngine/gameEngine.ts
> Add Sorceror deck

- src/client/components/TopNavBar/TopNavBar.tsx
Accidentally put the parentheses in the JSX in, which caused a layout issue
> Fix: name display regression

- src/cardDb/units/units.ts
- src/constants/deckLists.ts
- src/types/effects.ts
makes 'feed team' work instead of hanging
Closes: #189
> Fix: #189 , tweak farmers deck

- src/client/components/DeckListSelector/DeckListSelector.spec.tsx
- src/client/components/DeckListSelector/DeckListSelector.tsx
- src/client/components/DeckListSelector/index.ts
- src/client/components/Rooms/Rooms.tsx
part of #197
(no visible UI changes to client, refactor-only)
> Refactor: Extract out `DecklistSelector`

- src/client/components/App/App.tsx
- src/client/components/DeckList/DeckList.tsx
- src/client/components/DeckListSelector/DeckListSelector.tsx
- src/client/components/DeckManager/DeckManager.spec.tsx
- src/client/components/DeckManager/DeckManager.tsx
- src/client/components/DeckManager/index.ts
- src/client/components/SpellGridItem/SpellGridItem.tsx
- src/client/components/TopNavBar/TopNavBar.tsx
- src/client/redux/deckList/deckList.ts
- src/client/redux/selectors/getPremadeDeckList/getPremadeDeckList.spec.ts
- src/client/redux/selectors/getPremadeDeckList/getPremadeDeckList.ts
- src/client/redux/selectors/getPremadeDeckList/index.ts
- src/constants/lobbyConstants.ts
- src/server/sockets/sockets.ts
- src/test-utils/test-utils.tsx
Adds a place to preview a deck before you bring it into the game:
(new View Decklist link)
> Add decklist viewer component

- .github/workflows/ci.yml
- .gitignore
- jest.config.js
- package.json
- src/server/gameEngine/gameEngine.ts
- src/server/resolveEffect/resolveEffect.ts
> Improve CI performance

- src/client/components/RoomSquare/RoomSquare.spec.tsx
- src/client/components/RoomSquare/RoomSquare.tsx
- src/client/components/Rooms/Rooms.tsx
https://user-images.githubusercontent.com/1839462/159148496-a872d3bd-78bf-4c79-944b-15a69fb7628f.mov
> Add re-join room button

- .github/workflows/ci.yml
- src/client/components/GameDisplay/GameDisplay.spec.tsx
- src/client/components/GameDisplay/GameDisplay.tsx
- src/client/components/HandOfCards/HandOfCards.tsx
CSS changes for 3/4 player mode:
**3 player demo**
**4 player demo**
> 3 player + 4 player modes

- src/client/components/GameDisplay/GameDisplay.spec.tsx
- src/client/components/GameDisplay/GameDisplay.tsx
- src/client/components/RoomSquare/RoomSquare.spec.tsx
- src/client/components/RoomSquare/RoomSquare.tsx
- src/client/components/Rooms/Rooms.spec.tsx
- src/client/components/Rooms/Rooms.tsx
- src/client/components/WebSockets/WebSockets.tsx
- src/server/obscureBoardInfo/obscureBoardInfo.ts
- src/server/sockets/socket.spec.ts
- src/server/sockets/sockets.ts
- src/types.ts
Lets players join as a spectator for a game (but only for one that has not started)
Closes: #103
**Lobby:**
**Spectator Mode in-game**
> Spectator mode

- src/client/components/CenterPromptBox/CenterPromptBox.spec.tsx
- src/client/components/CenterPromptBox/CenterPromptBox.tsx
- src/client/components/WebSockets/WebSockets.tsx
- src/server/sockets/sockets.ts
- src/test-utils/test-utils.tsx
- src/types.ts
> Add 'leave game' functionality when game is over

- src/client/components/GameChatMessages/GameChatMessages.spec.tsx
- src/client/components/GameChatMessages/GameChatMessages.tsx
- src/client/components/GameChatMessages/index.ts
- src/client/components/GameDisplay/GameDisplay.tsx
- src/client/components/WebSockets/WebSockets.tsx
- src/factories/chat/makeChatMessage.spec.ts
- src/factories/chat/makeChatMessage.ts
- src/server/sockets/sockets.ts
- src/test-utils/test-utils.tsx
- src/types.ts
- src/types/chat.ts
Closes: #167
Moves out GameChatMessages into a separate component from GameDisplay
https://user-images.githubusercontent.com/1839462/159212036-9049e1ed-f75c-4f25-9f0d-d803a55dbd51.mov
> Add player chats (in game)

- src/cardDb/units/units.ts
- src/constants/deckLists.ts
> Add 'falcon rider' unit

- src/client/components/Button/Button.tsx
- src/client/components/RoomSquare/RoomSquare.tsx
- removed box shadow from buttons
- make the lobby screen say 'Switch to spectating' if already joined
> Quick HTML/CSS changes (lobby screen)

- src/client/components/Rooms/Rooms.tsx
> Expand rooms container size

- src/client/components/CardFrame/CardFrame.tsx
- src/client/components/GameChatMessages/GameChatMessages.tsx
- src/client/components/Rooms/Rooms.tsx
- src/server/homepage.html
> Move to box-sizing: border-box

- src/client/components/LatestWinners/LatestWinners.spec.tsx
- src/client/components/LatestWinners/LatestWinners.tsx
- src/client/components/LatestWinners/index.ts
- src/client/components/Rooms/Rooms.spec.tsx
- src/client/components/Rooms/Rooms.tsx
- src/client/components/WebSockets/WebSockets.tsx
- src/client/redux/lobby/lobby.ts
- src/factories/games/calculateGameResult.ts
- src/factories/games/calculateGameResults.spec.ts
- src/factories/games/index.ts
- src/server/sockets/sockets.ts
- src/types.ts
- src/types/games.ts
> Add latest game winners feature

- src/audioHelpers/playAudio.ts
- src/client/components/CardFrame/CardFrame.tsx
- src/client/components/GameChatMessages/GameChatMessages.tsx
- src/client/components/GameManager/handleClickOnCard.spec.ts
- src/client/components/GameManager/handleClickOnCard.ts
- src/client/components/GameManager/handleClickOnPlayer.spec.ts
- src/client/components/GameManager/handleClickPlayer.ts
- src/client/components/IntroScreen/IntroScreen.spec.tsx
- src/client/components/IntroScreen/IntroScreen.tsx
- src/client/components/NameChanger/NameChanger.spec.tsx
- src/client/components/NameChanger/NameChanger.tsx
- src/client/components/WebSockets/WebSockets.tsx
- src/constants/lobbyConstants.ts
- src/constants/sounds.ts
- src/server/homepage.html
Added:
- Quattrocento and Lato fonts
- basic sound effects package for entering the lobby, starting a game, and attacking
- footer with attribution (creative commons licensed song)
New intro screen, w/ burn-in parchment paper effect: https://codepen.io/AgnusDei/pen/NWPbOxL
Sounds preview:
https://user-images.githubusercontent.com/1839462/160034899-33d82ccb-6c43-4fe3-8648-47f86617aae3.mov
> Add sounds effects and font

- src/audioHelpers/playAudio.ts
- src/cardDb/spells/spells.ts
- src/cardDb/units/units.ts
- src/constants/deckLists.ts
- Nerf sound levels
- make wind mage have more draw
- make monks have more 1-drops
- made captain of the guard easier to cast
- nerf water guardian by 1 casting cost
> Balance changes

- src/client/components/AdvancedResourceCardGridItem.tsx/AdvancedResourceCardGridItem.spec.tsx
- src/client/components/AdvancedResourceCardGridItem.tsx/AdvancedResourceCardGridItem.tsx
- src/client/components/CardGridItem/CardGridItem.tsx
- src/client/components/GameManager/GameManager.tsx
- src/client/components/GameManager/handleClickOnCard.ts
- src/client/components/PlayerBoardSection/PlayerBoardSection.tsx
- src/factories/deck/makeDeck.ts
- src/server/gameEngine/gameEngine.spec.ts
- src/server/gameEngine/gameEngine.ts
- src/types/gameActions.ts
Closes: #212
demo:
https://user-images.githubusercontent.com/1839462/161220894-c6d8ad7a-61b0-4255-b16e-c95fbe76e27d.mov
> Implement double-resource card tapping

- src/server/index.ts
> Add health check

- src/server/sockets/sockets.ts
> Send game results down to clients on connect

- src/server/resolveEffect/resolveEffect.spec.ts
- src/server/resolveEffect/resolveEffect.ts
> Fix draw_per_unit not causing game loss

- src/client/components/DeckListSelector/DeckListSelector.spec.tsx
- src/client/components/DeckListSelector/DeckListSelector.tsx
- src/constants/lobbyConstants.ts
- src/factories/board/makeNewBoard.ts
Having fate decide your class at the start of the game is a fun way to make the game more exciting
Closes: #258
> "Add random" class to premade decklists

- src/client/components/App/App.tsx
- src/client/components/CardGridItem/CardGridItem.tsx
- src/client/components/CompactDeckList/CompactDeckList.tsx
- src/client/components/DeckBuilder/DeckBuilder.spec.tsx
- src/client/components/DeckBuilder/DeckBuilder.tsx
- src/client/components/DeckBuilder/index.ts
- src/client/components/DeckList/DeckList.tsx
- src/client/components/DeckListSelector/DeckListSelector.tsx
- src/constants/deckLists.ts
- src/constants/lobbyConstants.ts
- src/factories/board/makeNewBoard.ts
- src/test-utils/test-utils.tsx
- src/types/cards.ts
https://user-images.githubusercontent.com/1839462/162104254-008f080e-390d-4e2e-a937-e838367e7864.mp4
Raw deck-builder component, no search or filters yet.
Lets players build constructed decks (we want to support draft in the future too)
> Deck builder component

- src/client/components/DeckBuilder/DeckBuilder.spec.tsx
- src/client/components/DeckBuilder/DeckBuilder.tsx
- src/test-utils/test-utils.tsx
Closes: #269
https://user-images.githubusercontent.com/1839462/163097227-160b6594-6679-4d7c-a463-f6b8578dddd5.mp4
> Import / export decklist feature

- src/client/components/DeckBuilder/DeckBuilder.spec.tsx
- src/client/components/DeckBuilder/DeckBuilder.tsx
- src/client/components/WebSockets/WebSockets.tsx
- src/client/redux/deckList/deckList.ts
- src/factories/board/makeNewBoard.spec.ts
- src/factories/board/makeNewBoard.ts
- src/server/sockets/sockets.ts
- src/test-utils/test-utils.tsx
- src/types/index.ts
Closes: https://github.com/lijim/monks-and-mages/issues/275
Not included yet:
- validation of decks https://github.com/lijim/monks-and-mages/issues/276
- show custom deck on lobby https://github.com/lijim/monks-and-mages/issues/277[](https://github.com/lijim)
https://user-images.githubusercontent.com/1839462/163307617-e9d4cd00-3432-4aba-8925-7e4409e3523c.mp4
> Choose custom deck feature

- src/client/components/DeckBuilder/DeckBuilder.spec.tsx
- src/client/components/DeckBuilder/DeckBuilder.tsx
- src/constants/gameConstants.ts
- src/factories/board/makeNewBoard.ts
- src/transformers/isDeckValidForFomat/index.ts
- src/transformers/isDeckValidForFomat/isDeckValidForFormat.spec.ts
- src/transformers/isDeckValidForFomat/isDeckValidForFormat.ts
- src/types/games.ts
Closes: #276
https://user-images.githubusercontent.com/1839462/163697391-b6c77884-51ec-45ff-ae5a-6247da72a40a.mov
> Add deck list validation

- src/client/components/DeckListSelector/DeckListSelector.spec.tsx
- src/client/components/DeckListSelector/DeckListSelector.tsx
> Reveal custom deck on lobby

- src/client/components/Rooms/Rooms.spec.tsx
- src/client/components/Rooms/Rooms.tsx
- src/server/sockets/sockets.ts
Fixes issue where custom rooms always truncated the first 7 characters.
Makes it possible to create/spectate custom rooms
> Fix custom room bugs

- src/client/components/AdvancedResourceCardGridItem.tsx/index.ts
- src/client/components/AdvancedResourceGridItem.tsx/AdvancedResourceGridItem.spec.tsx
- src/client/components/AdvancedResourceGridItem.tsx/AdvancedResourceGridItem.tsx
- src/client/components/AdvancedResourceGridItem.tsx/index.ts
- src/client/components/CardGridItem/CardGridItem.tsx
> Shorten "AdvancedResourceCardGridItem"

- src/client/components/DeckBuilder/DeckBuilder.spec.tsx
- src/client/components/TopNavBar/TopNavBar.tsx
The logout button on the customize deck / view decks views was only logging out but not taking the user back to the home screen
> Make logout button always work

- setupTests.ts
- src/client/components/DeckBuilder/DeckBuilder.spec.tsx
- src/client/components/DeckBuilder/DeckBuilder.tsx
- src/factories/board/makeNewBoard.spec.ts
Closes #284 and allows players to upload .txt files / download .txt files for the game
> Deck builder: Import / download functionality

- src/client/components/PlayerBriefInfo/PlayerBriefInfo.spec.tsx
- src/constants/gameConstants.ts
- src/factories/board/makeNewBoard.spec.ts
Bump starting life total to 20
Closes: #303
> Adjust Starting Life Total

- package.json
- src/client/components/CastingCost/CastingCost.tsx
- src/client/components/DeckBuilder/DeckBuilder.spec.tsx
- src/client/components/DeckBuilder/DeckBuilder.tsx
- src/client/components/DeckBuilderFilters/DeckBuilderFilters.tsx
- src/client/components/DeckBuilderFilters/index.ts
- src/client/redux/deckBuilderFilters/deckBuilderFilters.ts
- src/client/redux/deckBuilderFilters/index.ts
- src/client/redux/store.ts
- src/test-utils/test-utils.tsx
- src/transformers/filterCards/filterCards.ts
- src/transformers/filterCards/index.ts
- src/types/deckBuilder.ts
- yarn.lock
Closes: #308 and #307
https://user-images.githubusercontent.com/1839462/165230076-98729faa-13fa-4e37-98f8-13fb4e18e4ed.mov
> Deck builder filters

- src/client/components/CompactDeckList/CompactDeckList.tsx
Ginormous usability improvement for deck builder added
https://user-images.githubusercontent.com/1839462/165689269-e33a7922-f70b-40ee-9fa4-1f64d058175a.mov
Closes: #306
> Adding tooltips for deck builder component

- setupTests.ts
- src/client/components/DeckBuilder/DeckBuilder.spec.tsx
- src/client/components/DeckBuilder/DeckBuilder.tsx
Also: adds support for testing global.window alert events
Closes: #274 
https://user-images.githubusercontent.com/1839462/165694722-a1320602-0beb-47d9-9c4c-aff11e4130a6.mov
> Add warnings about improper deck imports

- .eslintrc.js
> Make unused imports an error

- src/client/components/GameManager/handleClickOnCard.spec.ts
- src/client/components/GameManager/handleClickOnCard.ts
- src/client/redux/clientSideGameExtras/clientSideGameExtras.ts
Fixes: #95
https://user-images.githubusercontent.com/1839462/165698236-1aeb9320-15c0-4e51-86f1-6f410e7001f4.mov
> Cancel attacks when casting a spell

- src/cardDb/spells/spells.ts
- src/cardDb/units/mages/fire.ts
Changes Fire Mage and Throw Shuriken
> Changes Fire Mage and Throw Shuriken

- src/cardDb/units/tribes/sorcerors.ts
- src/client/components/DeckBuilder/DeckBuilder.spec.tsx
- src/client/components/DeckBuilderFilters/DeckBuilderFilters.tsx
- src/client/redux/deckBuilderFilters/deckBuilderFilters.ts
- src/transformers/filterCards/filterCards.ts
- src/types/deckBuilder.ts
https://user-images.githubusercontent.com/1839462/167285898-c7179551-6819-4f79-8a81-2664f6ea7dec.mov
This will help us analyze the cost curves of different colors and promote color balance better!
> Resource cost filter

- src/transformers/splitDeckListToPiles/splitDeckListToPiles.ts
Before decklists would only sort by total cost:
Now they sort by: total cost first, then colors, then by name:
> Improve sorting of decklists

- src/cardDb/spells/spells.ts
zen stance should target own units, not any units
> Change to zen stance

- src/cardDb/spells/spells.ts
- src/cardDb/units/mages/crystal.ts
- src/cardDb/units/mages/water.ts
- src/cardDb/units/misc.ts
- src/cardDb/units/ranged.ts
Nerfs to some OP cards:
- merry rallier / rain of arrows / stone slinger / manta ray conjurer / team gathering /energy enhancer
Buff to 1 card:
- silent markswoman
> Nerfs (game balance)

- src/client/components/GameDisplay/GameDisplay.spec.tsx
- src/client/components/GameDisplay/GameDisplay.tsx
- src/client/components/LastPlayedCard/LastPlayedCard.tsx
- src/client/components/LastPlayedCard/index.ts
- src/client/components/WebSockets/WebSockets.tsx
- src/client/redux/clientSideGameExtras/clientSideGameExtras.ts
- src/server/gameEngine/gameEngine.spec.ts
- src/server/gameEngine/gameEngine.ts
- src/server/sockets/sockets.ts
- src/types/index.ts
Closes: #354
Are you tired of not knowing what flaming fireball hit your face as your opponent casts yet another burn spell?  Sweat no more!  This PR introduces a 'last played spell' component that helps players identify what is going on in the game
> Last played spell

- src/cardDb/resources/utilityLands.ts
- src/client/components/NameChanger/NameChanger.tsx
- src/types/cards.ts
Part of #237
Added some fields for artist name / artist URL / original image page
> Add attribution fields for stock photo artists

- src/client/components/LastPlayedCard/LastPlayedCard.tsx
> Fix: emoji backgrounds are blue

- src/server/resolveEffect/resolveEffect.spec.ts
- src/server/resolveEffect/resolveEffect.ts
The oracle is drawing every card right now - this fixes that
> Fix bug with the oracle

- src/client/components/WebSockets/WebSockets.tsx
- webpack.config.js
1. un-hard coded the audience variable
2. made it use getAccessTokenSilently for prod build
> Fix some bugs with auth

- src/client/components/WebSockets/WebSockets.tsx
Ran into these errors: `Uncaught (in promise) Error: Service not found: monks-and-mages-prod.us.auth0.com/api/v2/`
Hopefully this fixes it*
> explicitly use https://

- src/client/components/App/App.tsx
- src/client/components/CardFrame/CardFrame.tsx
- src/client/components/InstructionsPage/InstructionsPage.tsx
- src/client/components/InstructionsPage/index.ts
- src/client/components/NameChanger/NameChanger.spec.tsx
- src/client/components/NameChanger/NameChanger.tsx
- src/client/components/TopNavBar/TopNavBar.tsx
- src/constants/colors.ts
https://user-images.githubusercontent.com/1839462/170182262-ca633e1b-ab3a-4256-a765-7ec659e553f6.mov
Closes: #249 
Added an instructions page with links from both the homepage and the lobby page
> Add instructions page

- src/client/components/WebSockets/WebSockets.tsx
- src/client/redux/user/user.ts
- src/server/sockets/sockets.ts
- src/types/index.ts
- src/types/user.ts
Part of #379
We need to send the auth0 user_id down to the redux layer so that the React app knows to call the API the right way
> Send auth0 user ID to redux

- package.json
- src/apiHelpers/apiHelpers.ts
- src/apiHelpers/index.ts
- src/client/components/DeckBuilder/DeckBuilder.spec.tsx
- src/client/components/DeckBuilder/DeckBuilder.tsx
- src/client/components/SavedDeckManager/SavedDeckManager.tsx
- src/client/components/SavedDeckManager/index.ts
- src/client/redux/selectors/selectors.ts
- src/mocks/savedDecks.ts
- src/types/deckBuilder.ts
- yarn.lock
This PR uses SWR to retrieve decks (not display them yet, that will come with #385), closes: #386
- renamed myDecks -> currentDeck everywhere
- added MSW to test this feature in an integration-style fashion
> Make call to get decks with SWR

- src/client/components/DeckBuilder/DeckBuilder.spec.tsx
- src/client/components/DeckBuilder/DeckBuilder.tsx
- src/client/components/SavedDeckManager/SavedDeckManager.tsx
- src/client/components/SavedDeckSquare/SavedDeckSquare.tsx
- src/client/components/SavedDeckSquare/index.ts
- src/mocks/savedDecks.ts
- src/types/deckBuilder.ts
Adds the ability to load a saved deck:
https://user-images.githubusercontent.com/1839462/174523016-913dec61-80d8-4d95-8bbb-7bf827187094.mov
closes: #392
> Saved Deck component / Loading Decks

- src/client/components/SavedDeckSquare/SavedDeckSquare.tsx
Closes: #367
Allows users to delete decks:
https://user-images.githubusercontent.com/1839462/174713054-a2e95f22-08e5-4897-b9a3-d24c3aa0216f.mov
> Add delete functionality

- src/client/components/Button/Button.tsx
- src/client/components/DeckBuilder/DeckBuilder.tsx
- src/client/components/SavedDeckManager/SavedDeckManager.tsx
Adds ability to create a deck
Video demo:
https://user-images.githubusercontent.com/1839462/174717661-a84e9d87-38ba-422a-a537-473e6ff00276.mp4
> Add ability to save decks (POST)

- package.json
- src/apiHelpers/apiHelpers.ts
- src/client/components/PlayerBriefInfo/PlayerBriefInfo.tsx
- src/client/components/Rooms/Rooms.spec.tsx
- src/client/components/Rooms/Rooms.tsx
- src/client/components/SelfProfilePage/SelfProfilePage.tsx
- src/client/components/WebSockets/WebSockets.tsx
- src/client/hooks/useLoggedInPlayerInfo.ts
- src/factories/board/makeNewBoard.ts
- src/factories/player/makeNewPlayer.ts
- src/server/sockets/socket.spec.ts
- src/server/sockets/sockets.ts
- src/types/api/gameResults.ts
- src/types/api/index.ts
- src/types/api/users.ts
- src/types/index.ts
- src/types/players.ts
- yarn.lock
Creates ability for users to choose their own avatars via a PATCH request to the`/users/self/choose_avatar` endpoint:
> Feat: Add ability to choose avatars

- src/client/components/CenterPromptBox/CenterPromptBox.tsx
- src/server/gameEngine/gameEngine.spec.ts
- src/server/gameEngine/gameEngine.ts
The game is a little bit luck dependent, with players going to 5 or fewer cards at a significant disadvantage.
To make up for it, the game will now reward a "pity card" of 1 extra card to those unfortunate souls going to 5 cards or under during their mulligans
> Feat: Give players going to 5 or fewer cards a pity card

- src/client/components/DeckList/DeckList.tsx
- src/client/components/DraftingTable/DraftingTable.spec.tsx
- src/client/components/DraftingTable/DraftingTable.tsx
- src/client/components/DraftingTable/index.ts
- src/client/components/GameDisplay/GameDisplay.spec.tsx
- src/client/components/GameDisplay/GameDisplay.tsx
- src/client/redux/selectors/selectors.ts
- src/factories/board/makeNewBoard.ts
- src/server/gameEngine/gameEngine.spec.ts
- src/server/gameEngine/gameEngine.ts
- src/types/board.ts
- src/types/gameActions.ts
https://user-images.githubusercontent.com/1839462/224984300-0d14798e-d9b9-4b92-b0fe-806128ed5adc.mov
Adding the 'drafting' portion of draft mode.
The UI and web sockets changes here handle:
- the logic behind taking cards
- being able to spectate other players
> Feat: Draft mode - Card Selection Phase

- src/client/components/CompactDeckList/CompactDeckList.tsx
- src/client/components/DeckBuilder/DeckBuilder.spec.tsx
- src/client/components/DeckBuilder/DeckBuilder.tsx
- src/client/components/DeckList/DeckList.spec.tsx
- src/client/components/DeckList/DeckList.tsx
- src/client/components/DeckManager/DeckManager.tsx
- src/client/components/DraftingTable/DraftingTable.tsx
- src/client/components/GameDisplay/GameDisplay.spec.tsx
- src/constants/gameConstants.ts
- src/factories/board/makeNewBoard.spec.ts
- src/factories/board/makeNewBoard.ts
- src/server/gameEngine/gameEngine.spec.ts
- src/server/gameEngine/gameEngine.ts
- src/types/gameActions.ts
https://user-images.githubusercontent.com/1839462/225271088-efefa34e-7681-4414-abeb-cfb8a3b99beb.mov
https://user-images.githubusercontent.com/1839462/225271091-23e36d82-597c-4a23-b248-f74a17b6cc41.mov
- Adds a 'start deckbuilding' button that lets players switch from drafting into deckbuilding
- Adds 'submit deck' logic for draft mode.  Games start when deckbuilding is done for all players
> Feat: implement limited mode fully

- src/client/components/SavedDeckManager/SavedDeckManager.tsx
- src/client/components/SavedDeckSquare/SavedDeckSquare.tsx
We forgot to make the mutate's based on URL + accessToken.  This PR updates that
> Fix: fix glitched saved deck interactions
