- src/client/components/App/App.spec.tsx
- src/client/components/App/App.tsx
- src/client/components/IntroScreen/IntroScreen.tsx
- src/client/components/WebSockets/WebSockets.tsx
- src/client/components/WebSockets/index.ts
- src/client/redux/selectors.spec.ts
- src/client/redux/selectors.ts
- src/client/redux/store.ts
- src/server/homepage.html
- src/server/index.ts
- src/test-utils/index.ts
- src/test-utils/test-utils.tsx
- src/types.d.ts
In most games, you have the option to pick a name.
This commit adds:
- a WebSocket provider that provides down all descendant components (such as IntroScreen) a way to access methods (e.g. chooseName) associated with the socket connection
- we changed the intro screen to involve picking a name before seeing anything else.
demo:
https://user-images.githubusercontent.com/1839462/155854794-6f90f4fd-ba16-4382-a73f-59403c3e2090.mov
> Make name changing server-side

- src/client/components/App/App.spec.tsx
- src/client/components/App/App.tsx
- src/client/components/IntroScreen/IntroScreen.tsx
- src/client/components/Rooms/Rooms.tsx
- src/client/components/WebSockets/WebSockets.tsx
- src/client/redux/store.ts
- src/server/index.ts
- src/test-utils/test-utils.tsx
- src/types.d.ts
Cleanup around the way we consume the router from redux-first-history / react-router v6.
1. Adds a serverToClient event called startGame that makes all users in the room dispatch the history event of /ingame
2. On the app, I made a useEffect that pushes '/' on the initial load of the page.  I don't foresee a use for saving the memory right now, so we're going to merely dispatch this instead
3. Removed the Rooms display off IntroScreen and into the main App's Routes component.  Right now introScreen is more aptly 'LoginBar' b/c it's only handling where users set their names and log out
> Cleanup: Improved Routing Usage

- src/client/components/RoomSquare/RoomSquare.tsx
- src/client/components/Rooms/Rooms.tsx
- src/client/components/WebSockets/WebSockets.tsx
- src/client/redux/room/room.ts
- src/server/index.ts
- src/types.ts
I'm adding a serverToClientEvent method called updateBoard that updates sockets with a particular board state.
In order to integrate this, we need to add an import file to types.d.ts.  However, the moment that we have an import in a .d.ts file, it no longer becomes global:
https://stackoverflow.com/questions/39040108/import-class-in-definition-file-d-ts
Renamed it to just types.ts to reflect this
> Make type.d.ts a non-ambient file

- src/client/components/GameBoard/GameBoard.spec.tsx
- src/factories/board/index.ts
- src/factories/board/makeNewBoard.ts
- src/factories/player/index.ts
- src/factories/player/makeNewPlayer.ts
- src/server/obscureBoardInfo/index.ts
- src/server/obscureBoardInfo/obscureBoardInfo.spec.ts
- src/server/obscureBoardInfo/obscureBoardInfo.ts
- src/server/sockets/sockets.ts
Part of #13:
`
Write a function called obscureHiddenInfo that obscures the 'cardInHand' information for everyone except for players. Also obscure the 'cardsInDeck' for all players. This function should be used on the updateBoard ServerToClient event.
`
https://user-images.githubusercontent.com/1839462/156501223-09ca1f59-b14c-4285-9640-abc2f0b57e7d.mov
After this update, players should not be able to see private, server-side only info, specifically:
- other players' hands
- the order of cards in decks.
> Add board-obscuring logic

- README.md
- src/client/components/App/App.tsx
- src/client/components/GameBoard/GameBoard.tsx
- src/client/redux/selectors.spec.ts
- src/client/redux/selectors.ts
- src/server/index.ts
- webpack.config.js
This PR moves the logic for redirecting over into the express side, instead of the app side.
- Added selectors for displaying the current player + the other players.  Closes #38 
- light reconfiguration of GameBoard to demo showing off the current vs. other player paradigm
Next up:
https://github.com/lijim/monks-and-mages/issues/39
https://user-images.githubusercontent.com/1839462/156694896-7a5bdd9e-9301-4f9c-bd51-f321b4a2c6fb.mov
> Display current vs. other players

- src/client/components/GameBoard/GameBoard.spec.tsx
- src/client/components/GameBoard/GameBoard.tsx
- src/factories/board/makeNewBoard.spec.ts
- src/factories/board/makeNewBoard.ts
adds the concept of 'active player' into makeBoard, so that when we do #39, we have an active player to validate + a player to pass the turn to
> Add 'active player' logic

- src/client/components/GameBoard/GameBoard.tsx
- src/client/components/OtherPlayerBoard/OtherPlayerBoard.spec.tsx
- src/client/components/OtherPlayerBoard/OtherPlayerBoard.tsx
- src/client/components/OtherPlayerBoard/index.ts
- src/client/components/SelfPlayerBoard/SelfPlayerBoard.spec.tsx
- src/client/components/SelfPlayerBoard/SelfPlayerBoard.tsx
- src/client/components/SelfPlayerBoard/index.ts
- src/client/components/SpellGridItem/SpellGridItem.tsx
- src/client/redux/selectors.spec.ts
- src/client/redux/selectors.ts
- src/server/sockets/sockets.ts
Internal refactoring (not any external facing changes in the client except switching the order of self / other players)
- renamed `CurrentPlayerBoard` to `SelfPlayerBoard` and extracted it.  Current player felt like it described the player with `isActivePlayer=true`, rather than the "self" player, which represent's the user's player.  We had already called it `SELF_PLAYER` under `types/effects.ts` - this just makes everything more consistent.
- extracted OtherPlayersBoard out to an external component to make it easier to manage
Partly covers #37.
> Move out `SelfPlayerBoard` and `OtherPlayerBoard` sections

- src/client/components/GameDisplay/GameDisplay.tsx
- src/client/components/OtherPlayerBoard/index.ts
- src/client/components/OtherPlayerInfo/OtherPlayerInfo.spec.tsx
- src/client/components/OtherPlayerInfo/OtherPlayerInfo.tsx
- src/client/components/OtherPlayerInfo/index.ts
- src/client/components/PlayerBoardSection/PlayerBoardSection.spec.tsx
- src/client/components/PlayerBoardSection/PlayerBoardSection.tsx
- src/client/components/PlayerBoardSection/index.ts
- src/client/components/SelfPlayerBoard/index.ts
- src/client/components/SelfPlayerInfo/SelfPlayerInfo.spec.tsx
- src/client/components/SelfPlayerInfo/SelfPlayerInfo.tsx
- src/client/components/SelfPlayerInfo/index.ts
Refactors `OtherPlayerBoardSection` and `SelfPlayerBoardSection` to just be one `PlayerBoardSection` that unifies the two.
Closes #37 
Same as #53 visually, but this sets us up to implement #48
> Create PlayerBoardSection component

- src/client/components/GameDisplay/GameDisplay.tsx
- src/client/components/PlayerBriefInfo/PlayerBriefInfo.spec.tsx
- src/client/components/PlayerBriefInfo/PlayerBriefInfo.tsx
Shown: new part of the `PlayerBriefInfo` component:
> Visual updates for 'ResourcePool'

- src/server/gameEngine/gameEngine.spec.ts
- src/server/gameEngine/gameEngine.ts
- src/transformers/canPlayerPayForCard/canPlayerPayForCard.ts
- src/transformers/canPlayerPayForCard/canPlayerPayForCards.spec.ts
- src/transformers/payForCard/payForCard.spec.ts
- src/transformers/payForCard/payForCard.ts
Tweaks + tests to cover these scenarios to allow for paying the right price on units - previously, there were scenarios where users could pay for cards that they shouldn't have been able to, e.g. a card that costs 5 resources like a cannon, could have been paid for with 4 resources.
It's very easy to make bugs when designing a game engine.  This is why this project places a high emphasis on testing - it allows us to catch the bugs before they even show up.  And when we find bugs, we can add test coverage to make sure that they don't regress in the future
> Fix: correctly calculate deploying unit costs

- src/client/components/App/App.spec.tsx
- src/client/components/Button/Button.tsx
- src/client/components/Button/index.ts
- src/client/components/NameChanger/NameChanger.tsx
- src/client/components/SelfPlayerInfo/SelfPlayerInfo.tsx
- src/constants/colors.ts
- src/types/resources.ts
Old rough draft design:
New design, looks much improved, only missing a game banner / logo:
Used styled-components' "attributes" feature to make an extensible Button and a PrimaryColorButton
> Stylize intro screen

- README.md
- src/client/components/CardGridItem/CardGridItem.tsx
- src/client/components/GameManager/handleClickOnCard.ts
- src/client/components/PlayerBoardSection/PlayerBoardSection.tsx
- src/client/components/PlayerBriefInfo/PlayerBriefInfo.spec.tsx
- src/client/components/PlayerBriefInfo/PlayerBriefInfo.tsx
- src/client/redux/clientSideGameExtras/clientSideGameExtras.ts
- src/server/gameEngine/gameEngine.spec.ts
- src/server/gameEngine/gameEngine.ts
- src/transformers/canPlayerPayForCard/canPlayerPayForCard.ts
- src/transformers/canPlayerPayForCard/canPlayerPayForCards.spec.ts
- src/transformers/payForCard/payForCard.spec.ts
- src/transformers/payForCard/payForCard.ts
Remaining:
- implement "poisonous" attacks
- implement 'attack enemy player'
- implement '# of attacks left' indicator
- show chat messages about attacks
Future ideas:
- implement sounds for attacking (each creature should have a different one)
- implement "silent" mode
https://user-images.githubusercontent.com/1839462/157177033-8e30fd6d-6804-4167-96cc-8deff9886920.mov
> Implement perform attack vs. unit

- src/client/components/GameManager/handleClickOnCard.spec.ts
- src/client/components/GameManager/handleClickOnCard.ts
- src/client/components/SelfPlayerInfo/SelfPlayerInfo.spec.tsx
- src/client/components/SelfPlayerInfo/SelfPlayerInfo.tsx
- src/client/components/WebSockets/WebSockets.tsx
- src/test-utils/test-utils.tsx
- src/types.ts
- src/types/effects.ts
- Improved the render from test-utils so that tests that used it can access mock versions of the WebSockets context values.
- added some preliminary constants around effects, e.g. default targets, which ones auto-resolve
- blocked clicking on cards if there are active effects (#77)
- block pass turn button if effects exist - Closes #80
> Various effects resolutions solutions

- src/client/components/GameManager/handleClickOnCard.spec.ts
- src/client/components/GameManager/handleClickOnPlayer.spec.ts
- src/server/sockets/socket.spec.ts
- src/server/sockets/sockets.ts
- src/test-utils/test-utils.tsx
Closes: #33
- if a player leaves the game, their player is booted.  If every player leaves, the room shuts down the board for it
- this allows for testing the game on the browser without having to
- took a look at if I could include better tests for sockets.ts, but unfortunately anything involving 2+ client sockets was really hard to implement.  Anything with more than 1 call to the server and 1 call back from the server ended up being hefty and led to memory leaks and warning messages with the `A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown.` message in jest.  Investigated by looking at https://github.com/facebook/jest/issues/9473, but I couldn't find a good solution, so I went with having fewer, …
> 'Player leaves game' sad path

- src/client/components/GameManager/GameManager.spec.tsx
- src/client/components/GameManager/GameManager.tsx
- src/client/redux/selectors.spec.ts
- src/client/redux/selectors.ts
- src/server/resolveEffect/resolveEffect.ts
Closes: #99
Before (if there was an effect that targeted something invalid, e.g. 'return a unit back to its hand'), that effect would persist:
https://user-images.githubusercontent.com/1839462/157782997-785bead2-990f-4ed7-b73f-03df3e46b49a.mov
Now (the effect that is invalid fizzles):
https://user-images.githubusercontent.com/1839462/157782900-be6e6e53-b581-48ec-bfeb-1bbee97527e3.mov
> Auto-fizzle any effect without valid targets

- README.md
- package.json
- yarn.lock
- Fixes the version to v17.x for node: https://devcenter.heroku.com/articles/deploying-nodejs#specify-the-version-of-node
- ran into an error where I found that heroku was asking 'We will use "yarn" to install the CLI via "yarn add -D webpack-cli"' on the logs
After investigating further, I see from stackoverflow that heroku runs with NODE_ENV=production and that we need to tell it to install all our dev dependencies like so: https://stackoverflow.com/a/53326418
For: #105
> Set up scripts for Heroku

- package.json
Heroku prunes the dev dependencies after the build
According to https://devcenter.heroku.com/articles/nodejs-support:
`"heroku-cleanup": "echo This runs after Heroku prunes and caches dependencies."`
We were trying to install dev dependencies previously, but it got pruned b/c of the post-build step
> Move yarn install --dev command into cleanup stage

- src/server/index.ts
Ran into this error:
`Web process failed to bind to $PORT within 60 seconds of launch`
Fix was to use the port number that heroku uses: https://stackoverflow.com/a/15693371
> Add process.env.PORT

- src/client/components/CardFrame/CardFrame.tsx
- src/client/components/GameDisplay/GameDisplay.spec.tsx
- src/client/components/GameManager/GameManager.spec.tsx
- src/client/components/GameManager/handleClickOnCard.spec.ts
- src/client/components/GameManager/handleClickOnPlayer.spec.ts
- src/client/components/HandOfCards/HandOfCards.spec.tsx
- src/client/components/SelfPlayerInfo/SelfPlayerInfo.spec.tsx
- src/client/redux/selectors.spec.ts
- src/factories/board/makeNewBoard.spec.ts
- src/factories/board/makeNewBoard.ts
- src/server/gameEngine/gameEngine.spec.ts
- src/server/obscureBoardInfo/obscureBoardInfo.spec.ts
- src/server/resolveEffect/resolveEffect.spec.ts
- src/server/sockets/sockets.ts
Precursor work to #125 
I'd like to add a param to `makeNewBoard` called `deckListTitlesForPlayers`, but in order to do so with less tech-debt, we need to turn `makeNewBoard` into a unary function
> Refactor: turn `makeNewBoard` into a unary function

- src/client/components/App/App.spec.tsx
- src/client/components/App/App.tsx
- src/client/components/Button/Button.tsx
- src/client/components/IntroScreen/IntroScreen.tsx
- src/client/components/NameChanger/NameChanger.tsx
- src/client/components/RoomSquare/RoomSquare.spec.tsx
- src/client/components/RoomSquare/RoomSquare.tsx
- src/client/components/Rooms/Rooms.spec.tsx
- src/client/components/Rooms/Rooms.tsx
- src/constants/colors.ts
- src/constants/lobbyConstants.ts
- src/server/sockets/socket.spec.ts
- src/server/sockets/sockets.ts
- Added new colors / backgrounds / layouts to the lobby experience
- renamed the default rooms (server always includes these in the listRooms response):
- Aardvark Alley 🐜
- Beetle Boulevard 🪲 
- Cobra Castle 🐍
- Added logic to only display start button if the player is part of the game 
- Always sort the rooms alphabetically
Before (kind of bland / very minimal):
https://user-images.githubusercontent.com/1839462/158006413-f3e8a885-a6a6-4ff9-8a29-08c96f78882d.mov
Now (improved color schemes, layouts):
https://user-images.githubusercontent.com/1839462/158006434-769583de-b6fd-4f1d-9345-14c8bdb45bbd.mov
Precursor to #125
> Revamp lobby screen

- src/client/components/RoomSquare/RoomSquare.tsx
- src/client/components/Rooms/Rooms.tsx
Before:
After:
(made room names h2's instead of h1's, added backgrounds to some of the elements on the screen)
> Align rooms screen (lobby)

- src/client/components/Rooms/Rooms.spec.tsx
- src/client/components/Rooms/Rooms.tsx
- src/client/components/WebSockets/WebSockets.tsx
- src/client/redux/lobby/index.ts
- src/client/redux/lobby/lobby.ts
- src/client/redux/room/index.ts
- src/client/redux/store.ts
- src/constants/lobbyConstants.ts
Making rooms 'lobby' instead so that it can encompass more aspects of the lobby screen, e.g. deck list selection
Needed for #125
> Refactor: rename rooms slice to lobby slice

- src/client/components/HandOfCards/HandOfCards.tsx
> Improve HandOfCards' handling of small # of cards

- src/client/components/CompactDeckList/CompactDeckList.spec.tsx
- src/client/components/DeckList/DeckList.spec.tsx
- src/client/components/Rooms/Rooms.spec.tsx
- src/client/components/Rooms/Rooms.tsx
- src/constants/lobbyConstants.ts
- src/factories/board/makeNewBoard.spec.ts
- src/factories/board/makeNewBoard.ts
- src/factories/deck/makeDeck.ts
- src/mocks/spells.ts
- src/mocks/units.ts
- src/server/gameEngine/gameEngine.spec.ts
- src/server/resolveEffect/resolveEffect.spec.ts
- src/server/resolveEffect/resolveEffect.ts
- src/transformers/splitDeckListToPiles/splitDeckListToPiles.spec.ts
Bumps the number of deck lists up to 4, adds a ton of new units / spells.
Some rebalancing of spells / units
As it was cumbersome to use units and spells in the tests for the gameEngine, I made it so that SAMPLE_DECKLIST_1 was exclusively for testing purposes and made a separate mocks file that will be used permanently for gameEngine and resolveEffect tests
> Introduce more deck list variety

- src/server/resolveEffect/resolveEffect.spec.ts
- src/server/resolveEffect/resolveEffect.ts
Makes it so that the 'Rain of Arrows' spell works properly
https://user-images.githubusercontent.com/1839462/158033213-e3bb9770-645f-42c0-b55a-d338651acf82.mov
> Bug: fix "opposing units" target type

- src/client/components/CardFrame/CardFrame.tsx
- src/client/components/CardGridItem/CardGridItem.tsx
- src/client/components/HandOfCards/HandOfCards.tsx
- src/client/components/PlayerBoardSection/PlayerBoardSection.tsx
- src/client/components/ResourceCardGridItem/ResourceCardGridItem.tsx
- src/client/components/SpellGridItem/SpellGridItem.tsx
- src/client/components/UnitGridItem/UnitGridItem.tsx
Closes: #130
Made it so that CardGridItem is where all tooltip display handling will be handled (rather than HandOfCards).  This allows us to extend the tooltips to the cards rendered on PlayerBoardSection
Demo:
https://user-images.githubusercontent.com/1839462/158034300-f210070c-95f9-4e88-bfe9-e453aca43728.mov
> Show tooltips for unit cards on board

- src/client/components/Rooms/Rooms.tsx
- src/server/gameEngine/gameEngine.spec.ts
- src/server/gameEngine/gameEngine.ts
- src/server/resolveEffect/resolveEffect.spec.ts
- If a unit with poisonous attacks a buffed unit, it will now properly send it to the grave
- Boardwipe spells (rain of arrows) should properly wipe units out now (before only half were being sent to cemetary).  Closes: #144
- Make rooms "choose a name" input fit on Windows browsers (hopefully)
> Fixes for sending units to cemetary properly

- src/server/gameEngine/gameEngine.spec.ts
- src/server/gameEngine/gameEngine.ts
- src/server/obscureBoardInfo/obscureBoardInfo.spec.ts
- src/server/obscureBoardInfo/obscureBoardInfo.ts
- src/server/resolveEffect/resolveEffect.spec.ts
- src/server/resolveEffect/resolveEffect.ts
We previously manually calculated the number of cards in hand /deck to show to each player manually and it was tedious to maintain / sometimes inaccurate
This removes that logic in favor of calculating at the point where the server needs to send down obscured board information
> Bug: handle # of cards in hand / level at the `obscureBoardInfo` level

- src/cardDb/spells/spells.ts
- src/cardDb/units/units.spec.ts
- src/cardDb/units/units.ts
- src/client/components/CardFrame/CardFrame.tsx
- src/client/components/CastingCost/CastingCost.tsx
- src/client/components/SpellGridItem/SpellGridItem.tsx
- src/client/components/UnitGridItem/UnitGridItem.tsx
- src/server/gameEngine/gameEngine.ts
- src/server/resolveEffect/resolveEffect.spec.ts
- src/server/resolveEffect/resolveEffect.ts
- src/types/cards.ts
Closes: #84
Implements the powerful 'curse hand' ability that makes cards for a target player cost X more in their hand.
When cards are reset (e.g. go to cemetary, bounced, etc.) they get their original costs back.  In addition, an 'originalCost' was added to do on-the-fly calcuations of if costs were costing more than they did originally
> Implement 'curse hand' effect

- src/client/components/CardFrame/CardFrame.tsx
- src/client/components/HandOfCards/HandOfCards.tsx
- src/client/components/NameChanger/NameChanger.tsx
- src/client/components/ResourceCardGridItem/ResourceCardGridItem.tsx
- src/client/components/SpellGridItem/SpellGridItem.tsx
- src/client/components/UnitGridItem/UnitGridItem.tsx
- src/constants/colors.ts
- src/types/resources.ts
1.) highlight deployable resources / cards
Closes: #121
Closes: #122
https://user-images.githubusercontent.com/1839462/158269423-0726bf4d-178b-4f45-8e8b-e770e8ca455e.mov
2.) Improve color contrasts of `CardGridItem` cards
Closes: #149
https://user-images.githubusercontent.com/1839462/158269480-d23667e9-20b7-4a45-a55f-30dce9e16ec5.mov
3.) add animation to a resource tapping sideways
> Usability improvements

- src/client/components/CardFrame/CardFrame.tsx
- src/client/components/CardGridItem/CardGridItem.tsx
- src/client/components/HandOfCards/HandOfCards.tsx
- src/client/components/PlayerBoardSection/PlayerBoardSection.tsx
- src/client/components/ResourceCardGridItem/ResourceCardGridItem.tsx
- src/client/components/SpellGridItem/SpellGridItem.tsx
- src/client/components/UnitGridItem/UnitGridItem.spec.tsx
- src/client/components/UnitGridItem/UnitGridItem.tsx
- src/client/redux/selectors/getHighlightableCards/getHighlightableCards.spec.ts
- src/client/redux/selectors/getHighlightableCards/getHighlightableCards.ts
- src/client/redux/selectors/getHighlightableCards/index.ts
- src/client/redux/selectors/index.ts
- src/client/redux/selectors/selectors.spec.ts
- src/client/redux/selectors/selectors.ts
- src/server/sockets/sockets.ts
Closes: #154 (in spirit)
Demos:
Bonus - we now show which units are eligible to attack and which are eligible to defend + which ones can be targets of spells:
https://user-images.githubusercontent.com/1839462/158403219-5aab2a49-aedf-4de8-a833-8891cc8768d1.mov
> Indicate eligible attackers / defenders

- src/server/gameEngine/gameEngine.spec.ts
- src/server/gameEngine/gameEngine.ts
Bugfix (it was previously going in reverse order).  Reversing at the point of putting effects on the stack as I want the stack to just be able to pop() the latest effect off.  This way, the first effect on the stack is the first to pop off and execute
https://user-images.githubusercontent.com/1839462/158517136-87e3fca3-0358-4400-90d8-f27b5d6d3638.mov
> Make effects go from top to bottom

- src/client/components/HandOfCards/HandOfCards.tsx
- src/client/components/PlayerBoardSection/PlayerBoardSection.tsx
- src/server/resolveEffect/resolveEffect.spec.ts
- src/server/resolveEffect/resolveEffect.ts
https://user-images.githubusercontent.com/1839462/158714242-f53eeb07-3565-4071-84a1-0ca2f5c8a1bc.mov
Also:
- animate card drawing
https://user-images.githubusercontent.com/1839462/158714225-b46dc5be-85e6-48a1-aa2a-9e2aa6a2edf2.mov
- make resolveEffect gloss over the target if it was inferred from a default in the chat messages for resolveEffect
Future 4 player demo possibilities:
> Handle overflow of cards on board

- src/client/components/App/App.tsx
- src/client/components/IntroScreen/IntroScreen.spec.tsx
- src/client/components/IntroScreen/IntroScreen.tsx
- src/client/components/NameChanger/NameChanger.tsx
- src/client/components/RoomSquare/index.ts
- src/client/components/Rooms/Rooms.tsx
- src/client/components/TopNavBar/TopNavBar.spec.tsx
- src/client/components/TopNavBar/TopNavBar.tsx
- src/client/components/TopNavBar/index.ts
- src/client/components/UnitGridItem/UnitGridItem.spec.tsx
Closes: #28 
- Moves all concerns about the top nav bar (first screenshot below) away from the intro screen component (second screenshot below).  New component is called 'TopNavBar'
- added component tests to IntroScreen
- fixed the barrel file for RoomsSquare
> Refactor: split out IntroScreen component

- src/client/components/GameDisplay/GameDisplay.spec.tsx
- src/client/components/GameDisplay/GameDisplay.tsx
- src/client/components/WebSockets/WebSockets.tsx
- src/client/redux/board/board.ts
- src/factories/chat/index.ts
- src/factories/chat/makeChatMessage.spec.ts
- src/factories/chat/makeChatMessage.ts
- src/server/gameEngine/gameEngine.spec.ts
- src/server/gameEngine/gameEngine.ts
- src/server/resolveEffect/resolveEffect.spec.ts
- src/server/resolveEffect/resolveEffect.ts
- src/server/sockets/sockets.ts
- src/types.ts
- src/types/chat.ts
1. Change everything from Msg to Message (code clarity)
2. Move chats from being a server-side store into being client-side only.
In preparation for: #167 as players could potentially send a large number of chats to each other
> Refactor: don't store chats in-memory (server)

- src/cardDb/units/units.ts
- src/constants/deckLists.ts
tweaks for:
Temple guardian 7 => 6 cost
Bamboo farmer (+1 health)
Stone slinger (+1 health)
wind mage (+1 cost)
farmer deck
(Add 2 rain of arrows, remove 2 temple guardian)
> balance patch (farmer deck)

- src/client/components/CenterPromptBox/CenterPromptBox.tsx
- src/client/components/TopNavBar/TopNavBar.tsx
- src/client/components/WebSockets/WebSockets.tsx
- src/client/redux/board/board.ts
- src/server/sockets/sockets.ts
Covers some of the 'sad paths' for joining / rejoining games
B/c of websockets being hard to test (async issues), we had many small little bugs that could cause rooms to be locked up in a 'started' state, or for players to see nothing when rejoining when using various combinations of the forward/back history buttons / log out / etc.
Fixed:
- type safety bugs where the CenterPromptBox (mulligan box) would cause crashes under various circumstances
- player disconnects by going back via browser tab history, switching rooms, and then leaving (whenever a player logs out / starts a new game / ) => game persists as started in room
- player logs out, rejoins a game, starts and sees a blank screen (this was just b/c the link was '#') Closes: #112 
- players both log out, and rejoin under new names …
> Fixes: room joining/rejoining logic

- src/client/components/DeckListSelector/DeckListSelector.spec.tsx
- src/client/components/DeckListSelector/DeckListSelector.tsx
- src/client/components/WebSockets/WebSockets.tsx
- src/client/redux/deckList/deckList.ts
- src/client/redux/deckList/index.ts
- src/client/redux/store.ts
- src/server/sockets/sockets.ts
- src/types.ts
Puts the decklist selection into a new slice called decklist.  In the future, this will include custom decklists, but for now, it just has the premade decklist
Part of #197 - we need this so that we have a sense of what decklist to display for the top-level router component that displays the decklist
> Make deck list selection redux-based

- README.md
- src/cardDb/spells/spells.ts
- src/cardDb/units/units.ts
- src/client/components/CardFrame/CardFrame.tsx
- src/client/components/PlayerBoardSection/PlayerBoardSection.tsx
- src/client/components/Rooms/Rooms.tsx
- src/constants/deckLists.ts
- src/server/gameEngine/gameEngine.ts
- src/server/resolveEffect/resolveEffect.spec.ts
- src/server/resolveEffect/resolveEffect.ts
- src/transformers/splitDeckListToPiles/splitDeckListToPiles.ts
- src/transformers/transformEffectsToRulesText/transformEffectsToRulesText.ts
- src/transformers/transformEffectsToRulesText/transformEffectstoRulesText.spec.ts
- src/types/effects.ts
added a card called Merry Rallier that draws per unit
https://user-images.githubusercontent.com/1839462/159174448-a7f2b744-8212-4fb3-9ce0-1c757fa827bd.mov
- tweaking the monk deck to have fewer resources and more draw
- made the assassin units easier to cast (more generic resources)
- fixed a bug where spell damage didn't cause a loss for opponents
- made generous geyser heal the player for 2
- made a gentle gust focused on buffing attack of units
- made the attack hp footer bigger and easier to view
> Draw per card effect

- src/cardDb/spells/spells.ts
- src/cardDb/units/units.ts
- src/client/components/CardFrame/CardFrame.tsx
- src/client/components/GameChatMessages/GameChatMessages.tsx
- src/client/components/UnitGridItem/UnitGridItem.tsx
- src/constants/deckLists.ts
- src/constants/lobbyConstants.ts
- src/server/resolveEffect/resolveEffect.spec.ts
- src/server/resolveEffect/resolveEffect.ts
- src/transformers/transformEffectsToRulesText/transformEffectsToRulesText.ts
- src/transformers/transformEffectsToRulesText/transformEffectstoRulesText.spec.ts
- src/types/cards.ts
- src/types/effects.ts
- fix chat CSS issue (the new send chat box was blocking overflow from being able to scroll)
- sizes the images on unit cards to take up more space
- adds a new 'coral' flavored deck (water + bamboo)
- balanced the open nebula spell to be less symmetrical
- added a new 1-drop unit for water (rowboat rower), a new 5-drop for water/bamboo (deep sea explorer), and a new 4 drop unit for scholars (practical scholar)
New divers deck:
> Add 'learn' effect

- src/cardDb/units/units.ts
- src/constants/deckLists.ts
- src/constants/lobbyConstants.ts
- src/server/resolveEffect/resolveEffect.spec.ts
- src/server/resolveEffect/resolveEffect.ts
- src/transformers/transformEffectsToRulesText/transformEffectsToRulesText.ts
- src/transformers/transformEffectsToRulesText/transformEffectstoRulesText.spec.ts
- src/types/effects.ts
The extract card effect can extract a card (or multiple cards) of a specific name and remove it from a deck (or decks)
- added a 'cannoneers' deck to go along with the new card (Quarry Miner)
> Add 'extract card' effect

- src/cardDb/spells/spells.ts
- src/cardDb/units/units.ts
- src/constants/deckLists.ts
- src/server/resolveEffect/resolveEffect.ts
In playtesting, divers and farmers were head and shoulders above the rest of the decks, with fire mage and genies being the least competitive.
Nerfs to farmers / divers:
- ramp effect comes in tapped
- nerfed divers by increasing deep sea explorer by 1
- bamboo farmer (most OP unit) reduced health to 1
Monks:
- tweaked monks deck to have more draw
Fire mage deck:
- tweaked fire mages deck to have more board clears
- reduced cost of inferno sorceror by 1
- made 'curse hand' easier to cast
Genies deck:
- added 'distort reality'
- made open nebula more powerful, but more expensive (has a hard removal aspect now)
Misc:
- renamed Practical scholar to bright scholar to fit the card better
- cannoneers gets a new card 'ignite sparks' that allows flexible removal
> Balance tweaks

- src/server/sockets/sockets.ts
- webpack.config.js
Turns out that trying to resolve effects for closed boards was a source of several node-server failures. This adds some short-circuit logic to that controller and adds a source-map to better identify future bugs/crashes
Closes:
#239
> Fix crashes in game + add source maps

- .github/workflows/ci.yml
push is good enough and the CI check on pull request is often superfluous / slowing me down when it already does CI checks with every push
> Remove pull_request from CI flow

- src/transformers/transformEffectsToRulesText/transformEffectsToRulesText.ts
- src/transformers/transformEffectsToRulesText/transformEffectstoRulesText.spec.ts
makes it so the default is not just 'ANY' anymore
Makes displaying rules for implicit 'self player' better.
Closes: #264 < before the rules text defaulted to 'any target', but it didn't make any sense in the context of 'any target's magic units' (vs `your magic units`, which makes way more sense).  This fixes that
> TransformEffectToRulesText => uses defaults

- src/client/components/CompactDeckList/CompactDeckList.tsx
- src/client/components/DeckBuilder/DeckBuilder.spec.tsx
- src/client/components/DeckBuilder/DeckBuilder.tsx
- src/client/components/DeckList/DeckList.tsx
- src/transformers/getColorForCard/getColorForCard.spec.ts
- src/transformers/getColorForCard/getColorForCard.ts
1. Dual colors on CompactDeckList advanced resource cards
2. Fix bug with not being able to add more than 1 of any card (except for basic resources)
3. Make DeckList return blank component if no cards are in it yet
> Fix bugs with deck builder

- src/client/components/AdvancedResourceGridItem.tsx/AdvancedResourceGridItem.tsx
- src/client/components/App/App.tsx
- src/client/components/CardGridItem/CardGridItem.tsx
- src/client/components/CompactDeckList/CompactDeckList.tsx
- src/client/components/ResourceCardGridItem/ResourceCardGridItem.tsx
- src/client/components/SpellGridItem/SpellGridItem.tsx
- src/client/components/UnitGridItem/UnitGridItem.tsx
- src/server/homepage.html
Closes: #70 
Big accessibility update for keyboard-only users.  The whole game can be played sans mouse now thanks to the magic of `tabIndex` in HTML.
Notes on a11y research:
1. TabIndex's are a good thing (this is a11y 101) => your users should be able to navigate your entire site sans-mouse for a11y reasons and also personal ergonomics
1. A problem arises when you want to do tabIndexes and let users use the Enter key to press on divs (yes, I know buttons/links are better, but sometimes we really do need clickable divs, e.g. the playing cards in this game).
1. To that end I followed [this stack overflow answer](https://stackoverflow.com/questions/42034359/trigger-click-event-on-keypress-for-any-focused-element/62142145#62142145).  I improved upon it by using keyup instead of keypress …
> Add keyboard a11y

- src/client/components/DeckBuilder/DeckBuilder.spec.tsx
- src/client/components/DeckBuilderFilters/DeckBuilderFilters.tsx
- src/client/redux/deckBuilderFilters/deckBuilderFilters.ts
- src/transformers/filterCards/filterCards.ts
- src/transformers/getTypeForUnitCard/getTypeForUnitCard.spec.ts
- src/transformers/getTypeForUnitCard/getTypeForUnitCard.ts
- src/transformers/getTypeForUnitCard/index.ts
- src/types/cards.ts
- src/types/deckBuilder.ts
Introduces the search filter for unit type to the deck building UI
Closes: #309
Also: refactoring some of the helpers (e.g. getTypeForUnitCard)
Learning: use .includes instead of ".indexOf(x) > -1" - way more readable
https://user-images.githubusercontent.com/1839462/165686399-54fa5b9c-c18a-4405-bc9c-c433c810947c.mov
> Search by unit type

- src/cardDb/units/units.ts
- src/server/resolveEffect/resolveEffect.spec.ts
- src/server/resolveEffect/resolveEffect.ts
- src/transformers/transformEffectsToRulesText/transformEffectsToRulesText.ts
- src/transformers/transformEffectsToRulesText/transformEffectstoRulesText.spec.ts
- src/types/effects.ts
Bamboo farmer was one of the most powerful units in the game that essentially ramped for 1 a single resource and put a 1/1 body on the board.
Now, it's more reasonable, because it has a real deck-building constraint.
It ramps from the hand instead now, greatly increasing non-bamboo design space
> Nerf bamboo farmer

- src/server/gameEngine/gameEngine.spec.ts
- src/server/gameEngine/gameEngine.ts
- src/transformers/transformEffectsToRulesText/transformEffectsToRulesText.ts
- src/transformers/transformEffectsToRulesText/transformEffectstoRulesText.spec.ts
- src/types/effects.ts
1. Hearty should not re-order units on losing hearty
used red-green to properly set up the test first for this scenario, then re-worked the logic to account for
2. hearty doesn't get permanently lost - updated wording
3. Chad no longer misleadingly says 'increase water resources by 1' but instead 'increase water resources by 1 for all opponents'
> Minor gameplay bug fixes

- src/server/resolveEffect/resolveEffect.spec.ts
- src/server/resolveEffect/resolveEffect.ts
When effects had an implicit target (e.g. 'ANY' for dealing damage), the previous system would not be good about displaying the target in the chat.
This is b/c we wanted to simplify originally the target of 'you' for drawing cards, e.g. we don't want to display `resolved: draw 2 cards -> you`.  when we could just say `resolved: draw 2 cards`
This led to shorthanded cards with real targets, e.g. `deal 2 damage` not having a proper chat message
> Fix implicit target chat messages (effects)

- src/cardDb/spells/spells.ts
Some of the 3 color-cards had overwhelming amounts of text.
Auditing and making their effects easier to grok for players
> Balance: simplify 'underworld message'

- src/server/resolveEffect/resolveEffect.ts
Bamboo farmer was able to somehow ramp out bamboo footbridges.  This fixes that
> Disallow advanced resource cards from being ramped

- src/cardDb/resources/advancedResources.ts
- src/client/components/DeckBuilder/DeckBuilder.spec.tsx
- src/client/components/InstructionsPage/InstructionsPage.tsx
- src/client/components/PlayerBriefInfo/PlayerBriefInfo.spec.tsx
- src/constants/deckLists.ts
- src/constants/gameConstants.ts
- src/constants/lobbyConstants.ts
- src/factories/board/makeNewBoard.spec.ts
- src/factories/board/makeNewBoard.ts
- src/transformers/isDeckValidForFomat/isDeckValidForFormat.spec.ts
Originally, I had wanted the game to feel "unique" from Magic (which has a 60 card deck) and I had landed on a 48-card deck size.
The problem with 48 cards is that it makes decks feel repetitive when you can have 4-of's in a deck.  It also doesn't allow the whole card-pool to shine as much.
- Bumped the deck minimum size to 60
- Made the dual lands that come in untapped deal 2 damage to the user
- Added a "pirates" deck
> Feat: Bump decklist size to 60

- src/client/components/GameManager/GameManager.spec.tsx
- src/client/redux/selectors/selectors.ts
- src/constants/deckLists.ts
- src/constants/lobbyConstants.ts
Found this while play-testing.
Closes: #360
We had an issue where effects (like Old Farmhouse's "buff attack" effect) would linger on the game client if they didn't have a target type specified (we use `getDefaultTargetForEffect` for these types of effects).
Fixed this by adding the logic in for grabbing the default targets in the useEffect that handles fizzling the effects that don't have valid targets.
What the "linger" state looks like - game is unable to proceed:
> Fix issue where effects would linger without a valid target

- src/client/components/CardGridItem/CardGridItem.spec.tsx
- src/client/components/CardGridItem/CardGridItem.tsx
- src/client/components/SavedDeckSquare/SavedDeckSquare.tsx
Soldier, ranged, and magical are a little confusing to new players.  We added some help text to units on board to assist with displaying them
> Feat: add helper text on cards

- src/client/components/DeckBuilder/DeckBuilder.spec.tsx
- src/client/components/DeckBuilder/DeckBuilder.tsx
- src/client/components/SavedDeckManager/SavedDeckManager.tsx
- src/client/components/SavedDeckSquare/SavedDeckSquare.tsx
this adds a 'clear' button to the deck builder, which was missing before.
Previously players had to exit the deck builder to clear their deck, which was a very time consuming process
https://user-images.githubusercontent.com/1839462/221165927-2110006e-2ade-410a-908b-9659c09de7b7.mov
> Add clear deck functionality to deck builder

- src/server/sockets/sockets.ts
- src/types/api/gameResults.ts
- src/types/api/index.ts
This adds an POST call to the DB server whenever a game is decided by a game action (either resolving effect or taking a game action, like attacking)
It does not* call the game recording if the game is decided by a disconnect (to prevent XP farming)
> Feat: Add game recording

- src/client/components/SelfProfilePage/SelfProfilePage.spec.tsx
- src/client/components/SelfProfilePage/SelfProfilePage.tsx
The Profile Page was crashing b/c the first load of the `useLoggedInPlayerInfo` hook was returning null.  Added some defensive programming checks to bail out early in the component if the returned value was null
Also: added a test for this to fix it fully:
> Fix: Don't crash on initial load for /me page

- src/client/components/SelfProfilePage/SelfProfilePage.tsx
- src/client/hooks/useLoggedInPlayerInfo.ts
- src/types/players.ts
New: adding the bottom text to the avatars in the profile page (displaying the names of the avatars / associated levels)
> Feat: Display avatar names on profile page

- src/client/components/CenterPromptBox/CenterPromptBox.spec.tsx
- src/client/components/CompactDeckList/CompactDeckList.spec.tsx
- src/client/components/CompactDeckList/CompactDeckList.tsx
- src/client/components/DeckBuilder/DeckBuilder.spec.tsx
- src/client/components/DeckBuilder/DeckBuilder.tsx
- src/client/components/DeckList/DeckList.tsx
- src/client/components/SavedDeckManager/SavedDeckManager.tsx
- src/client/components/SavedDeckSquare/SavedDeckSquare.tsx
- src/client/components/SelfPlayerInfo/SelfPlayerInfo.spec.tsx
- src/client/components/SelfProfilePage/SelfProfilePage.spec.tsx
- src/client/components/SelfProfilePage/SelfProfilePage.tsx
- src/client/redux/deckBuilder/deckBuilder.ts
- src/client/redux/deckBuilder/index.ts
- src/client/redux/selectors/deckBuilder.ts
- src/client/redux/selectors/deckList.ts
- src/client/redux/selectors/index.ts
- src/client/redux/store.ts
- src/test-utils/test-utils.tsx
- src/types/games.ts
Made a big refactor to use redux everywhere for the deck builder in order to add highlighted state to the Saved Deck component.
This was done in preparation for #389, as in order to let users edit a deck, we need to have a concept of which deck it is that they're editing
It makes the most sense to do this all inside of Redux because:
1.) It's easy to visually inspect and debug
2.) We were doing a bunch of prop pass-downs inside of the DeckBuilder's component tree.  This allows us to lift state up into redux and not do those pass-downs (e.g. addCard, removeCard, setSkeleton, etc.)
https://user-images.githubusercontent.com/1839462/221841354-2d39917f-5ce3-48f5-af72-bed6c24f68df.mov
> Feat: Highlight the selected deck

- src/client/components/SavedDeckManager/SavedDeckManager.tsx
- src/client/components/SavedDeckSquare/SavedDeckSquare.tsx
- src/client/redux/deckBuilder/deckBuilder.ts
- src/client/redux/selectors/deckBuilder.ts
- src/types/api/api.ts
- src/types/api/index.ts
Closes: #389 
Lets users save existing decks alongside the API updates here: https://github.com/lijim/monks-and-mages-db-service/pull/28
> Feat: allow users to update existing decks

- src/server/gameEngine/gameEngine.ts
- src/server/resolveEffect/resolveEffect.spec.ts
- src/server/resolveEffect/resolveEffect.ts
- src/server/sockets/sockets.ts
Our logic for detecting whether players won was previously very 2-player centric, which caused a number of bugs related to players leaving or losing the game in multiplayer.
If a player abandoned a 3 player game, but was the active player, it would cause a state where neither of the remaining players could do anything (like mulligan, play the game, etc.) - see the state below:
https://user-images.githubusercontent.com/1839462/222680275-6a97c948-a012-4078-bd17-3556f5cddf4c.mov
We've fixed it so that now, if a player abandons the game, the game continues playing on until there is a winner:
https://user-images.githubusercontent.com/1839462/222678250-61529f68-df73-4516-b456-6937c048bd87.mov
Closes: #256 
Any effect that causes the game to check a win state (e.g. drawing the last card in a …
> Fix: Gracefully handle abandons in multiplayer / improve "win state" logic

- src/client/components/CardFrame/CardFrame.tsx
- src/client/components/DeckBuilderFilters/DeckBuilderFilters.tsx
- src/constants/colors.ts
Having an element with `transform: rotate(45deg)` for the tilted squares representing rarity in the last PR (#415) introduced a visual bug on the deck builder / viewer:
This is because we rely on successive zIndex's to stack the cards on top of each other, but transform creates a new stacking context for zIndex.
We switched to using an SVG based diamond instead to solve this:
> Fix: use SVG over transform to prevent z-Index issues

- src/cardDb/spells/spells.ts
- src/client/components/Pack/Pack.tsx
- src/constants/deckLists.ts
- src/factories/index.ts
- src/factories/pack/index.ts
- src/factories/pack/makePack.ts
- src/types/cards.ts
New factory method In preparation for Draft / limited mode
Built a "makePack" factory that allows us to generate a pack of 15 cards - 9 commons, 4 uncommons, and either 2 rares or 1 rare/mythic.
> Feat: add pack generation helpers

- README.md
- src/client/redux/board/board.ts
- src/constants/gameConstants.ts
- src/factories/board/makeNewBoard.spec.ts
- src/factories/board/makeNewBoard.ts
- src/factories/player/makeNewPlayer.ts
- src/server/obscureBoardInfo/obscureBoardInfo.ts
- src/server/sockets/sockets.ts
- src/types/board.ts
In this game, everything in the game that is displayed derives from the state of the Board object, as passed from the server, calling the obscureBoardInfo helper to obscure critical pieces of information (e.g. opponent's hand, etc.).
Game actions from the client are sent as actions to the server, which calculate a potential new game board state to display/
When approaching the challenge of building "draft" mode, a logical place to start is to modify and expand the concept of the "Board" objects to encapsulate everything to do with drafting - draft pool, draft piles, etc.
Players also get an update in that they have a `deckBuildingPool` property as well, which starts as a blank array (or an array of 6 packs for sealed mode).
This PR upgraded the makeNewBoard / makeNewPlayer to account for …
> Feat: Helpers for creating a "drafting" / "sealed" experience

- src/client/components/CompactDeckList/CompactDeckList.spec.tsx
- src/client/components/CompactDeckList/CompactDeckList.tsx
- src/client/components/DeckBuilder/DeckBuilder.tsx
- src/client/components/DraftingTable/DraftingTable.tsx
- src/client/components/GameDisplay/GameDisplay.spec.tsx
- src/client/components/GameDisplay/GameDisplay.tsx
- src/client/components/QuantitySelector/QuantitySelector.tsx
- src/client/redux/board/board.ts
- src/client/redux/selectors/deckBuilder.ts
- src/client/redux/selectors/selectors.ts
- src/constants/deckLists.ts
- src/constants/gameConstants.ts
- src/transformers/isDeckValidForFomat/isDeckValidForFormat.ts
- Extended `DeckBuilder` and `CompactDeckList` to allow users to construct decks for Draft and Sealed mode.
- Rendered them when the game's state is "deckbuilding"
Next up:
- Add a game action for completing deckbuilding ("submit deck") and wire it up to the submit button
- Add a game action for finishing up draft ("finish draft") and add UI for it
> Feat: Deckbuilder UI for Draft / Sealed mode

- src/client/components/CompactDeckList/CompactDeckList.tsx
- src/client/components/DeckBuilder/DeckBuilder.spec.tsx
- src/client/components/DeckListSelector/DeckListSelector.spec.tsx
- src/client/redux/deckBuilder/deckBuilder.ts
- src/client/redux/selectors/deckBuilder.ts
- src/constants/deckLists.ts
- src/factories/board/makeNewBoard.spec.ts
- src/factories/deck/makeDeck.spec.ts
- src/factories/deck/makeDeck.ts
- src/factories/player/makeNewPlayer.spec.ts
- src/mocks/savedDecks.ts
- src/transformers/getDeckListFromSkeleton/getDeckListFromSkeleton.spec.ts
- src/transformers/getDeckListFromSkeleton/getDeckListFromSkeleton.ts
- src/transformers/getSkeletonFromDeckList/getSkeletonFromDeckList.spec.ts
- src/transformers/getSkeletonFromDeckList/getSkeletonFromDeckList.ts
- src/transformers/isDeckValidForFomat/isDeckValidForFormat.spec.ts
- src/transformers/isDeckValidForFomat/isDeckValidForFormat.ts
- src/transformers/splitDeckListToPiles/splitDeckListToPiles.spec.ts
- src/types/cards.ts
As I started working on draft mode, I thought it would be nice to support sideboards in the future in case players wanted to play best of 3 or even best of 5.
This update doesn't add sideboards in per se, but it does allow for the possibility of it in the future.
With Typescript, it was very easy to change the structure of `DeckList` and `Skeleton` to take a new structure.
The rest was paint-by-the-numbers using jest:watch to fix all the places where everything needed updating.
Before - decklist was an array:
Now - decklist is an Object with a main board + sideboard array:
> Feat: Future proof game for sideboards

- src/client/components/CompactDeckList/CompactDeckList.tsx
On https://github.com/lijim/monks-and-mages/pull/421, we introduced having 0.7 opacity for cards that had no onClick, but our logic was flawed in that it prevented places like the regular deck builder (not draft mode's deck builder) from having proper tinting on the CompactDeckList component:
This patch introduces logic to consolidate where we do an early return in onClick and make that the basis for whether to display cursor: pointer / have higher/lower opacity
> Fix: patch opacity regression for deck builder

- src/client/components/CompactDeckList/CompactDeckList.tsx
It was possible to get into this state if playing a round of draft right after playing sealed.
Now we'll check to make sure that the game state is in deckbuilding before using subtraction logic to determine card quantities
> Fix: Display proper numbers when drafting after playing limited

- src/client/components/LogoutButton/LogoutButton.tsx
- src/client/components/TopNavBar/TopNavBar.spec.tsx
- src/client/components/TopNavBar/TopNavBar.tsx
- src/client/components/WebSockets/WebSockets.tsx
- src/server/sockets/sockets.ts
- src/test-utils/test-utils.tsx
- src/types/sockets.ts
Another step towards allowing users to reconnect to games.  Users will now be able to refresh and see the same name as they had before, thanks to implementing some client-side persistence of socket.auth variables in local storage.  Prior to this PR, we had stored them in local storage, but never used them.
In this PR:
- When the game loads, the game reads the session ID from cache.  It sends the socket the auth variables and tries to connect. If successful, the server emits a 'session' event that sets the username in redux, so that the client can display it / redirect to the main game page
- When the user manually logs out, it clears both local storage AND fires off a disconnect event, resetting the server-side store
- When the user refreshes / disconnects for any reason other than a …
> Feat: Add persistent sessions

- src/cardDb/spells/spells.ts
- src/cardDb/units/mages/crystal.ts
- src/cardDb/units/mages/water.ts
- src/cardDb/units/misc.ts
- src/cardDb/units/ranged.ts
- src/cardDb/units/soldiers.ts
Attempting to balance each mono-color card identity to have:
- 16 commons
- 9 uncommons
- 6 rares
- 1 mythic
We had a few outliers (e.g. Green having 9 rares / 8 uncommons) where I've deemed it necessary to shift some of the cards to other rarities to balance the game out
> Feat: downshift cards in rarity

- src/cardDb/spells/spells.ts
- src/cardDb/units/mages/fire.ts
- src/cardDb/units/mages/water.ts
- src/cardDb/units/ranged.ts
- src/cardDb/units/tribes/sorcerors.ts
After playtesting - a few cards need nerfing.
Curious researcher feels like a better version of a 2/2 draw a card for 3.  It has too much upside for no downside, so nerfing it to 4 mana.
Lu Zishen is too strong as a 3/3 - since it hits twice, it can deal a whopping 6 damage when ahead, while also taking out 4 damage worth of opposing units
Penelope the Tortoise receives a buff - healing for 4, drawing one less card (3 -> 2)
The 'draw per unit' cards, Merry Rallier and Team Gathering, have been made to cost 1 less.  These cards are difficult currently to get to in terms of mana cost compared to their upside, and need to be slightly more accessible
> Feat: Nerf / buff cards

- src/apiHelpers/apiHelpers.ts
- src/client/components/SavedDeckManager/SavedDeckManager.tsx
- src/client/components/SavedDeckSquare/SavedDeckSquare.tsx
- src/client/components/SelfProfilePage/SelfProfilePage.tsx
- src/client/components/TopNavBar/TopNavBar.tsx
- src/client/components/WebSockets/WebSockets.tsx
- src/client/hooks/useLoggedInPlayerInfo.ts
**Problem**
Normally, a connected user looks like this:
But sometimes, a user can get in a state where they have a sessionID still remembered in local storage, without proper auth0 cookies and we wind up in this state:
This is annoying to deal with as we debug because it's hard to tell if the user is logged in at a first glance (they're half-logged in in the sense that the game server remembers their sessionID, but they lack auth0 authentication, so they'll lack avatar setting / saved deck selections, etc.)
**Solution**
1.) Although it's not efficient, I made all the SWR fetcher's function factories that generate each time the components re-renders.  This mitigates an issue where sometimes the components render and don't have access to the cookie yet, necessitating a refresh.  The idea …
> Fix: mitigate stale connections issue

- src/server/gameEngine/gameEngine.spec.ts
- src/server/gameEngine/gameEngine.ts
- src/server/resolveEffect/resolveEffect.spec.ts
- src/server/resolveEffect/resolveEffect.ts
- src/types/cards.ts
Players going first have a massive advantage in this game because of the 'hearthstone' like mechanics where being the first on board means you can dictate combat
To balance this out, I've added in 2 player games a rule that players going second receive a 'riches' card after their mulligans (add one generic resource)
In 3+ player games, the players going 2nd will get just a landmark -aka (2) draw a card.  Players going 3rd / 4th will get riches
> Feat: add additional cards for players not going first (balance)

- src/client/components/CardFrame/CardFrame.tsx
- src/client/components/DeckBuilder/DeckBuilder.spec.tsx
- src/client/components/DeckBuilderFilters/DeckBuilderFilters.tsx
- src/server/gameEngine/gameEngine.spec.ts
- src/server/gameEngine/gameEngine.ts
- src/transformers/filterCards/filterCards.spec.ts
- src/transformers/filterCards/filterCards.ts
- src/types/cards.ts
- src/types/deckBuilder.ts
In the deck builder component, our previous 'strict' and 'loose' filters for resources turned out to be impractical for deckbuilding - for instance, if one wanted to build a blue/green deck, the filters would send them in the direction of any card having at least blue OR green.  What we really wanted was a filter to say, give me Blue cards / green cards / blue+green cards.
This overhaul gets rid of the 3 filters (exact, strict, loose) in favor of just exact (all resources selected must match) and loose (the cards must fall under the resources selected, but can be missing some)
Before:
https://user-images.githubusercontent.com/1839462/229257678-1c7319a3-118c-4662-92f3-9d9116b695d3.mov
After:
https://user-images.githubusercontent.com/1839462/229257743-1dafa3e3-c55c-45f8-81ab-b3e2cb315203.mov …
> Feat: Improve filter cards by resource 

- src/client/components/GameManager/GameManager.tsx
- src/constants/gameConstants.ts
- src/server/sockets/sockets.ts
- src/server/stores/roomStore.ts
- src/transformers/transformEffectsToRulesText/transformEffectsToRulesText.ts
- src/types/effects.ts
**Problem**
In real testing on the actual domain, (not on local) we were able to reproduce twice cards with multiple effects (such as martial trainer, deep sea diver) causing a chain of effects where the latests effects didn't match properly, triggering a state where the game was rendered unplayable.
The reason was that our resolveEffect handler on the sockets connection was setting board to null. This meant whenever the game server was trying to emit the board for the room, it would exit early and not do anything.
**How did we fix it?**
To prevent this we added a series of guardrails:
1. Increased the timeout to 1250ms, from 1000ms for resolving effects automatically.  While in ideal world, the automatic effect resolution should be guided by the server side, we have yet to implement it …
> Fix: Prevent effect resolution ending games prematurely

- src/cardDb/units/tribes/dragons.ts
Accidentally put one of the legendary units as an uncommon
> Fix: swap rarities

- src/client/components/PlayerBriefInfo/PlayerBriefInfo.spec.tsx
- src/client/components/PlayerBriefInfo/PlayerBriefInfo.tsx
- src/factories/board/makeNewBoard.ts
- src/factories/cards/makeCards.ts
- src/factories/player/makeNewPlayer.spec.ts
- src/factories/player/makeNewPlayer.ts
- src/server/gameEngine/gameEngine.ts
- src/transformers/filterCards/filterCards.ts
- src/transformers/index.ts
- src/transformers/isCardLegendary/index.ts
- src/transformers/isCardLegendary/isCardLegendary.ts
- src/transformers/isDeckValidForFomat/isDeckValidForFormat.spec.ts
- src/transformers/isDeckValidForFomat/isDeckValidForFormat.ts
- src/types/board.ts
- src/types/cards.ts
This PR introduces support for the 'legendary leader' of the 'legendary league' mode in both the game board API and in the game itself:
Next PR's:
- highlight the legendary leader if its cost is payable (extract isCardDeployable into transformers)
- add an action to deploy the legendary leader
- add opacity to the legendary leader if it is deployed
- add cleanup logic to return legendary leaders back when they are destroyed
> Feat: Introduce support for 'legendary leader'

- src/cardDb/units/misc.ts
- src/server/resolveEffect/resolveEffect.spec.ts
- src/server/resolveEffect/resolveEffect.ts
- src/transformers/transformEffectsToRulesText/transformEffectsToRulesText.spec.ts
- src/transformers/transformEffectsToRulesText/transformEffectsToRulesText.ts
- src/types/cards.ts
- src/types/effects.ts
Adding a bunch of new effect types for cards I've brainstormed
Next up:
- adding them into the rules language models
- adding them into the rules engine (resolveEffect.ts)
- adding 'for each' multipliers (new feature for effects to describe ways of scaling effects)
- implementing the 'snowblind' mechanic
- ensuring that units with poisonous when dealing damage via effects destroy opposing units
> Feat: Add 25+ new effect types

- src/cardDb/resources/utilityLands.ts
- src/cardDb/spells/spells.ts
- src/cardDb/units/misc.ts
- src/cardDb/units/tribes/dragons.ts
- src/cardDb/units/tribes/pirates.ts
- src/cardDb/units/units.spec.ts
- src/client/components/SpellGridItem/SpellGridItem.tsx
- src/client/components/UnitGridItem/UnitGridItem.tsx
- src/factories/cards/makeCards.ts
- src/server/gameEngine/gameEngine.ts
- src/server/resolveEffect/resolveEffect.spec.ts
- src/server/resolveEffect/resolveEffect.ts
- src/transformers/joinPhrases/joinPhrases.ts
- src/transformers/transformEffectsToRulesText/transformEffectsToRulesText.spec.ts
- src/transformers/transformEffectsToRulesText/transformEffectsToRulesText.ts
- src/types/cards.ts
- src/types/effects.ts
- src/types/resources.ts
This update adds in all the NLP-like rules constructions to the 25+ new effects added in #453.  No player-facing changes yet - we still need to implement the cards that use these new effects as well as adding in support for these new effects on an engine-level
- Also adds in support for resetting units' types (a pre-emptive move to support the implementation of the 'gain magical' and 'lose magical/ranged' effects) + smarter unit/spell resetting when moving cards from hand to cemetery
Next up:
- Adding new effects into the rules engine (resolveEffect.ts)
- Adding 'for each' multipliers (new feature for effects to describe ways of scaling effects)
- Implementing the 'snowblind' mechanic
- Ensuring that units with poisonous when dealing damage via effects destroy opposing units
- Adding in …
> Feat: Update rules text engine to support 25+ new effects added

- src/transformers/getColorIdentityForCard/getColorIdentityForCard.spec.ts
- src/transformers/getColorIdentityForCard/getColorIdentityForCard.ts
Closes: #462 
Similar to MTG, establishing color identity for a card should only be for a color symbol.  E.g. if the card says 4🌊: Add 🔥, it would have a 🌊/🔥 identity.  But if it says, 4🌊: Destroy a fire resource.  That would be a color identity for the legendary leaders format of just 🌊
> Fix: Color identity should only be for effects with symbols

- src/server/gameEngine/gameEngine.ts
Modulo doesn't work with negative numbers in Javascript, causing some issues with players in 3/4 player games not getting their starting bonuses for not going 1st.
So trying to calculate the "starting position" by subtracting indexes can result in negative positions.
Example:
starting player is index 2
player A is index 0.
player B is index 1
player C is index 3
While player C will be correctly calculated as having a "positionAfterStartingPlayer" of 1, player B would be -1
This change fixes that by adding the total number of players before doing the modulo operator
> Fix: fix 3-player/4-player games bonuses for not going 1st
